queue_rules:
  - name: default # automatic merge for master when reviewed and CI passes
    queue_conditions:
      - label=ready-to-merge
    merge_conditions:
      - "#approved-reviews-by>=1"
      - base=master
    merge_method: squash

pull_request_rules:
  - name: delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}
  - name: ask developers to resolve conflict
    conditions:
      - conflict
      - -author~=^dependabot(|-preview)\[bot\]$
    actions:
      comment:
        message: This pull request has a conflict. Could you fix it @{{author}}?
