name-template: "v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
categories:
  - title: "Dependency Updates"
    labels:
      - "dependencies"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
template: |
  ## What's New

  $CHANGES
