FROM node:lts as builder

WORKDIR /src
USER 0

COPY package.json yarn.lock lerna.json tsconfig.json .prettierrc ./
COPY apps/frontend ./apps/frontend
COPY libs ./libs

RUN yarn --frozen-lockfile

RUN yarn frontend build

# production stage
FROM nginx:stable-alpine as production-stage
COPY --from=builder /src/dist/frontend /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
