ARG BUILD_CONTAINER=node:lts-alpine
ARG BASE_CONTAINER=nginx:1.18.0-alpine

FROM $BUILD_CONTAINER as builder

ARG YARNREPO_MIRROR=https://registry.yarnpkg.com
ENV YARNREPO=$YARNREPO_MIRROR

WORKDIR /src
USER 0

COPY package.json yarn.lock lerna.json tsconfig.json .prettierrc ./
COPY apps/frontend ./apps/frontend
COPY libs ./libs

RUN sed -i s^https://registry.yarnpkg.com^$YARNREPO^g yarn.lock
RUN yarn --frozen-lockfile --production --network-timeout 600000

RUN yarn frontend build

# production stage
FROM $BASE_CONTAINER as production-stage
COPY --from=builder /src/dist/frontend /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
