
import e18e from '@e18e/eslint-plugin';
import comments from '@eslint-community/eslint-plugin-eslint-comments/configs';
import js from '@eslint/js';
import json from '@eslint/json';
import markdown from '@eslint/markdown';
import stylistic from '@stylistic/eslint-plugin';
import vitest from '@vitest/eslint-plugin';
import eslintConfigPrettier from 'eslint-config-prettier/flat';
import {
  createTypeScriptImportResolver,
  defaultExtensions,
} from 'eslint-import-resolver-typescript';
import { importX } from 'eslint-plugin-import-x';
import markdownLinks from 'eslint-plugin-markdown-links';
import markdownPreferences from 'eslint-plugin-markdown-preferences';
import n from 'eslint-plugin-n';
import promise from 'eslint-plugin-promise';
import regexp from 'eslint-plugin-regexp';
import security from 'eslint-plugin-security';
import unicorn from 'eslint-plugin-unicorn';
import yml from 'eslint-plugin-yml';
import { defineConfig } from 'eslint/config';
import tseslint from 'typescript-eslint';
import cypress from 'eslint-plugin-cypress';
import vue from 'eslint-plugin-vue';

export default defineConfig([
  {
    // `docs` is the VitePress documentation site (ADR-005 §2.1): an isolated
    // project with its own package.json, lockfile and toolchain, deliberately
    // outside the workspaces globs. This config's typed linting cannot parse
    // its .vitepress sources (they belong to no tsconfig project), and its
    // markdown answers to the docs build — `yarn build` inside docs/, with
    // dead-link checking — not to the application's markdown rules.
    ignores: [
      '**/dist',
      '**/lib',
      '**/node_modules',
      'libs/inspecjs/src/generated_parsers/**',
      'docs/**',
      // Static DATA tables and generated sources — extending the
      // generated_parsers precedent directly above. These hold no logic, so
      // linting them yields no correctness signal (TypeScript still type-checks
      // them); what it did yield was 36k formatting complaints that buried the
      // real findings. NiktoNistMappingData.ts alone produced 26,836 messages —
      // 17,882 "use single quotes" and 8,941 "don't quote props", i.e. exactly
      // 3 per data row. Scoped to the *MappingData.ts suffix on purpose: the
      // sibling *Mapping.ts / *MappingItem.ts files ARE logic and stay linted.
      '**/*MappingData.ts',
      'libs/hdf-converters/src/ckl-mapper/jsonixMapping.ts', // "Generated by jsonix-schema-compiler"
      'apps/frontend/src/utilities/cci_util.ts', // 14k-line CCI_DESCRIPTIONS table, zero functions
      'libs/hdf-converters/schemas/**/jsonix-compiler-output/**', // same generator as jsonixMapping.ts
      'libs/hdf-converters/data/reverse-html-mapper/tw-elements.min.js', // vendored minified bundle
      'libs/hdf-converters/sample_jsons/**', // mapper fixture corpus — inputs under test, not code
    ],
    name: 'global ignores',
  },
  {
    extends: [
      js.configs.recommended,
      tseslint.configs.recommendedTypeChecked,
      vitest.configs.recommended,
      promise.configs['flat/recommended'],
      { ...regexp.configs.all, name: 'regexp/all' },
      unicorn.configs.recommended,
      n.configs['flat/recommended'],
      {
        ...stylistic.configs.customize({
          braceStyle: '1tbs',
          indent: [2, { SwitchCase: 1 }],
          quoteProps: 'as-needed',
          quotes: 'single',
          semi: true,
        }), name: '@stylistic/customized',
      },
      tseslint.configs.stylisticTypeChecked,
      comments.recommended,
      yml.configs.standard.map((config) => ({...config, name: 'yml/standard'})),
      security.configs.recommended,
      importX.flatConfigs.recommended,
      importX.flatConfigs.typescript,
      // perfectionist's preset is deliberately NOT extended. Its sort-* rules
      // carry zero correctness value and every one is a `suggestion`-type
      // autofix — the AST-rewriting class ESLint's own docs say must not be
      // auto-applied when "a fix potentially changes functionality". In this
      // repo they did exactly that: sort-decorators reordered sequelize
      // decorators and the whole backend suite stopped collecting;
      // sort-classes landed in an unsatisfiable conflict with
      // unicorn/consistent-class-member-order; sort-objects reordering object
      // literals contributed to a typing break in evaluations.service.ts.
      // sort-objects is also unsound in principle — key order is semantic
      // across a spread ({...defaults, mode} !== {mode, ...defaults}).
      // The import-ordering rules were kept at first, then dropped too:
      // sort-imports MOVES side-effect imports, which are order-dependent.
      // Verified by dry run — it relocated `import '@mdi/font/...css'` behind
      // the vuetify import in plugins/vuetify.ts, reordering the CSS cascade,
      // and ControlRowDetails.vue has five prismjs imports where the core must
      // load before its language components register onto it. No sort-* rule
      // here can reach zero without rewriting order that carries meaning.
      // e18e is adopted for its UNIQUE value only (2026-08-13 triage, Aaron:
      // one generalist plugin, specialists per domain, extras curated
      // rule-by-rule). Its modernization category is NOT extended — all ten
      // rules re-check what unicorn/typescript-eslint already own, so the
      // same site reported 3-5x (prefer-includes: unicorn + ts + e18e).
      // Wholesale-extending an overlapping preset was the perfectionist
      // mistake repeated. Two perf-category duplicates are disabled below.
      { ...e18e.configs.performanceImprovements, name: 'e18e/performanceImprovements' },
      cypress.configs.recommended,
      vue.configs['flat/vue2-recommended'],
    ],
    files: ['**/*.{js,mjs,cjs,ts,mts,cts,vue}'],
    languageOptions: {
      ecmaVersion: 'latest',
      parserOptions: { 
        extraFileExtensions: ['.vue'],
        parser: tseslint.parser,
        projectService: { 
          allowDefaultProject: [
            'apps/frontend/vue.config.js',
            'eslint.config.mjs',
            'libs/password-complexity/index.js',
            'vitest.config.ts',
          ]
        }
      },
      sourceType: 'module',
    },
    name: 'js/ts',
    rules: {
      '@stylistic/eol-last': 'error',
      '@stylistic/object-curly-newline': ['error', { multiline: true }],
      '@stylistic/quotes': ['error', 'single', { avoidEscape: true }],
      // Per-package below (2026-08-13 triage, Aaron) — this global default
      // covers packages not scoped there. Measured usage decides direction.
      '@typescript-eslint/consistent-type-definitions': ['error', 'type'],
      // e18e duplicates disabled — the specialist owns each check:
      // regexp/prefer-regexp-test (regexp plugin) and unicorn/prefer-array-some.
      'e18e/prefer-regex-test': 'off',
      'e18e/prefer-array-some': 'off',
      // Uint8Array.fromBase64/toBase64 is TC39 Stage 4 but UNDEFINED at this
      // repo's Node floor (22.18; 24.x in use) — the Buffer forms the rule
      // flags are the correct code today. Revisit when the floor includes the
      // API (2026-08-13 triage, Aaron).
      'unicorn/prefer-uint8array-base64': 'off',
      '@typescript-eslint/consistent-type-exports': 'error',
      '@typescript-eslint/consistent-type-imports': 'error',
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-redundant-type-constituents': 'off',
      '@typescript-eslint/no-unsafe-argument': 'off',
      // The underscore prefix is the ecosystem's explicit intentionally-unused
      // marker and this codebase already uses it (interface-conforming params,
      // watcher signatures, mock methods). Honoring it is the rule's own
      // documented configuration; unmarked unused vars still flag.
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          args: 'all',
          argsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
          destructuredArrayIgnorePattern: '^_',
          varsIgnorePattern: '^_',
        },
      ],
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-call': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-return': 'off',
      '@typescript-eslint/prefer-nullish-coalescing': 'off',
      curly: 'error',
      'n/no-missing-import': ['error', { tryExtensions: ['.ts', '.tsx', '.d.ts', '.js', '.jsx', '.mjs', '.cjs', '.json'] }],
      'prefer-object-has-own': 'error',
      // kebabCase is the rule's own default, what NestJS generates
      // (schematics normalizeToKebabOrSnakeCase dasherizes camelCase), and
      // what this repo already is: apps/backend/src alone has 56 kebab-case
      // files and zero snake_case. The previous snakeCase setting matched
      // nothing and produced 343 errors — hidden until `|| true` was removed
      // from lint:ci. Packages with a different measured convention get
      // scoped case unions below (Aaron, 2026-08-13 triage: zero renames).
      'unicorn/filename-case': ['error', { case: 'kebabCase' }],
      // 2026-08-13 triage (Aaron): dropped as vocabulary opinion — 281 hits
      // meant mass-renaming exported symbols and Vue props for zero behavior
      // gain.
      'unicorn/name-replacements': 'off',
      // 2026-08-13 triage (Aaron): same class as name-replacements — is/has
      // prefix enforcement renames public-ish booleans (Vue props, mapper
      // options) for zero behavior gain.
      'unicorn/consistent-boolean-name': 'off',
      'unicorn/no-null': 'off',
      'unicorn/no-process-exit': 'off',
      // 2026-08-13 triage (Aaron): style family dropped — zero correctness
      // value and every fixer is suggestion-type (AST-rewriting).
      // no-useless-else's fixer DESTROYS continue statements (inspecjs stack
      // overflow; docs/development/eslint-config-decisions.md hazard #6).
      'unicorn/no-for-each': 'off',
      'unicorn/no-useless-else': 'off',
      'unicorn/prefer-node-protocol': 'off',
      'unicorn/prefer-ternary': 'off',
      'unicorn/prevent-abbreviations': 'off',
      'unicorn/switch-case-braces': 'off',
      // 2026-08-13 triage (Aaron): adding u/v flags to 180 working legacy
      // regexes (144 in hdf-converters mappers) is 180 semantic changes each
      // needing per-pattern equivalence proof against golden fixtures — cost
      // far exceeds value. New code can adopt the flags freely.
      'regexp/require-unicode-regexp': 'off',
      'regexp/require-unicode-sets-regexp': 'off',
    },
    // Without this, import-x/n resolve imports from the REPO ROOT and never see
    // apps/frontend/tsconfig.json, where `@/*` -> `./src/*` is defined. Every
    // `@/...` import in the frontend then reports as unresolved — ~744 errors
    // for imports that resolve correctly in every real build. Listing each
    // package's tsconfig lets the resolver pick the one closest to the file
    // being linted (see the resolver's affinity sorting).
    settings: {
      // lodash is CommonJS and builds its export object dynamically, so
      // import-x cannot statically enumerate its members. With 62 files doing
      // `import * as _ from 'lodash'`, import-x/namespace reported 797 errors
      // of the form "'get' not found in imported namespace '_'" — for
      // functions that demonstrably exist (`typeof _.get === 'function'`).
      // Every one was a false positive. This is the rule's documented escape
      // hatch for modules whose exports can't be analyzed; it is scoped to
      // lodash, so namespace checking stays active for every other module.
      'import-x/ignore': ['lodash'],
      'import-x/resolver-next': [
        createTypeScriptImportResolver({
          extensions: [...defaultExtensions, '.vue'],
          noWarnOnMultipleProjects: true,
          project: [
            'tsconfig.json',
            'apps/*/tsconfig.json',
            'libs/*/tsconfig.json',
            'test/tsconfig.json',
          ],
        }),
      ],
    },
  },
  {
    // Sequelize migrations are plain CJS scripts outside every tsconfig, so
    // the type-aware projectService fatals on all ~31 of them ("was not found
    // by the project service") and they were silently not linted at all.
    // disableTypeChecked is typescript-eslint's documented answer for files
    // outside the project: full linting minus the rules that need type info.
    // Sequelize migrations and seeders are plain CJS scripts outside every
    // tsconfig, so the type-aware projectService fatals on all of them ("was
    // not found by the project service") and they were silently not linted at
    // all. disableTypeChecked is typescript-eslint's documented answer for
    // files outside the project: full linting minus the rules needing type
    // info.
    extends: [tseslint.configs.disableTypeChecked],
    files: [
      'apps/backend/migrations/**/*.js',
      'apps/backend/seeders/**/*.js',
    ],
    languageOptions: { parserOptions: { projectService: false } },
    name: 'ts/sequelize-scripts-untyped',
    rules: {
      // The standard sequelize signature is (queryInterface, Sequelize) and
      // ~31 shipped migrations never use the second param. Editing historical
      // migrations is churn on files nobody should touch (Aaron, 2026-08-13
      // triage) — ignore that one name here; real unused vars still flag.
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_|^Sequelize$' }],
      // A migration's filename is an identifier stored in the SequelizeMeta
      // table on every deployment (seeders likewise in SequelizeData) —
      // renaming one causes it to re-run. The names are frozen data, not a
      // style choice.
      'unicorn/filename-case': 'off',
    },
  },
  {
    // Same project-service fatal, different remedy: these loose CJS scripts
    // (Lite's npm-shipped server, PostCSS config, test support servers, the
    // FIPS bench spike) are real code and keep every rule — they just cannot
    // have type-aware linting, belonging to no tsconfig project.
    extends: [tseslint.configs.disableTypeChecked],
    files: [
      'apps/frontend/src/server.js',
      'packaging/**/*.js',
      'postcss.config.js',
      'test/support/**/*.js',
    ],
    languageOptions: { parserOptions: { projectService: false } },
    name: 'ts/loose-cjs-scripts-untyped',
  },
  {
    // The same loose CJS scripts, plus vue.config.js (CJS by webpack
    // contract): __dirname/module.exports are correct here — same rationale
    // as the backend/libs scope-off above.
    files: [
      'apps/frontend/src/server.js',
      'apps/frontend/vue.config.js',
      'packaging/**/*.js',
      'postcss.config.js',
      'test/support/**/*.js',
    ],
    name: 'unicorn/loose-cjs-prefer-module',
    plugins: { unicorn },
    rules: { 'unicorn/prefer-module': 'off' },
  },
  {
    // consistent-type-definitions per MEASURED package majority (2026-08-13
    // triage, Aaron — zero-churn philosophy, same as filenames): frontend
    // 40:16, inspecjs 43:1 and common are interface codebases; backend (21:0
    // type) and hdf-converters (39:29 type) keep the global 'type'. The
    // interface->type fixer is the one that broke declare-module before —
    // never run it across module augmentations.
    files: [
      'apps/frontend/**/*.{ts,vue}',
      'libs/common/**/*.ts',
      'libs/inspecjs/**/*.ts',
    ],
    name: 'ts/interface-packages',
    rules: {
      '@typescript-eslint/consistent-type-definitions': ['error', 'interface'],
    },
  },
  {
    // Mapper pipelines nest calls as a deliberate style; extracting named
    // intermediates at 130 sites is churn, not clarity (2026-08-13 triage,
    // Aaron). The handful of hits elsewhere get fixed by hand.
    files: ['libs/hdf-converters/**'],
    name: 'unicorn/hdf-nested-calls',
    plugins: { unicorn },
    rules: { 'unicorn/max-nested-calls': 'off' },
  },
  {
    // Filename-case unions per package, from MEASURED conventions (2026-08-13
    // triage, Aaron: zero renames). Each union is that package's existing
    // styles — the rule still blocks any NEW style from appearing. Measured:
    // frontend .vue 95/95 PascalCase (Vue's own style-guide convention);
    // frontend .ts snake/flat/Pascal mix; hdf-converters src kebab-majority
    // with PascalCase classes and 3 camel; hdf-converters test 33/35
    // snake_case (*_mapper.spec.ts); inspecjs flat/snake/kebab; test/
    // Pascal-majority. Backend stays strict kebab via the global rule.
    files: ['apps/frontend/**/*.vue'],
    name: 'unicorn/filename-vue',
    plugins: { unicorn },
    rules: {
      'unicorn/filename-case': ['error', { cases: { kebabCase: true, pascalCase: true } }],
    },
  },
  {
    files: ['apps/frontend/**/*.ts'],
    name: 'unicorn/filename-frontend-ts',
    plugins: { unicorn },
    rules: {
      'unicorn/filename-case': ['error', { cases: { kebabCase: true, pascalCase: true, snakeCase: true } }],
    },
  },
  {
    files: ['libs/hdf-converters/src/**'],
    name: 'unicorn/filename-hdf-src',
    plugins: { unicorn },
    rules: {
      'unicorn/filename-case': ['error', { cases: { camelCase: true, kebabCase: true, pascalCase: true } }],
    },
  },
  {
    files: ['libs/hdf-converters/test/**', 'libs/inspecjs/**'],
    name: 'unicorn/filename-snake-test-dirs',
    plugins: { unicorn },
    rules: {
      'unicorn/filename-case': ['error', { cases: { kebabCase: true, snakeCase: true } }],
    },
  },
  {
    files: ['test/**'],
    name: 'unicorn/filename-e2e',
    plugins: { unicorn },
    rules: {
      'unicorn/filename-case': ['error', { cases: { kebabCase: true, pascalCase: true } }],
    },
  },
  {
    // Cypress specs assert through cy.should chains and page-object
    // verifiers, which the vitest heuristic cannot see — vitest's
    // expectation rules do not apply to Cypress files.
    files: ['**/*.cy.ts'],
    name: 'vitest-off-for-cypress',
    plugins: { vitest },
    rules: {
      'vitest/expect-expect': 'off',
    },
  },
  {
    // Data, not code (2026-08-13 triage, Aaron: rename code, ignore data):
    // inspecjs parse_testbed fixtures and the vendor-shaped .d.ts type files
    // keep their upstream-derived names; README.md is the ecosystem
    // convention. Renaming data and docs is churn with no value.
    files: [
      '**/README.md',
      'libs/hdf-converters/types/**',
      'libs/inspecjs/parse_testbed/**',
    ],
    name: 'unicorn/filename-data',
    plugins: { unicorn },
    rules: {
      'unicorn/filename-case': 'off',
    },
  },
  {
    // import-x/no-named-as-default-member cautions that `plugin.configs` may
    // not survive some CJS/ESM interop paths. In this file the pattern
    // (`tseslint.configs...`, `yml.configs...`) is the flat-config idiom every
    // plugin's own documentation uses, and the rule's suggested named imports
    // would collide — six plugins here all export `configs`. Config file only;
    // application code keeps the rule.
    files: ['eslint.config.mjs'],
    name: 'import-x/flat-config-idiom',
    rules: { 'import-x/no-named-as-default-member': 'off' },
  },
  {
    // CommonJS entry scripts: nest builds the backend to CJS and the EC2
    // test-infra harnesses are plain CJS scripts, so top-level await does
    // not exist for them — `entry().catch(...)` is the entry idiom that
    // keeps a failed boot exiting nonzero instead of surfacing as an
    // unhandled rejection. File-scoped because that is eslint's granularity;
    // these files are thin entry shells, with the real logic in modules
    // that keep both rules.
    files: ['apps/backend/src/main.ts', 'packaging/test-infra/**/*.js'],
    name: 'unicorn/cjs-entry-points',
    plugins: { unicorn },
    rules: {
      'unicorn/prefer-await': 'off',
      'unicorn/prefer-top-level-await': 'off',
    },
  },
  {
    // security/detect-non-literal-fs-filename flags OWASP path traversal:
    // fs calls whose path an attacker might influence. In spec files the
    // paths are the test's own fixtures (tmpdir + literals) — there is no
    // attacker input by construction, and lint:ci's --max-warnings 0
    // escalates the rule's deliberate warn severity into a hard failure.
    // Production code keeps the warning.
    files: ['**/*.spec.ts', '**/*.spec.js', 'test/**', '**/test/**', '**/tests/**'],
    name: 'security/spec-fixture-paths',
    rules: {
      'security/detect-non-literal-fs-filename': 'off',
      // Same reasoning: test code indexes its own fixtures with its own loop
      // counters — there is no attacker input in a spec by construction.
      'security/detect-object-injection': 'off',
    },
  },
  {
    // Maintainer-run fixture conversion tooling (csv2json/xml2json): the
    // path arguments are the operator's own CLI inputs on their own machine —
    // never request data.
    files: ['libs/hdf-converters/data/**'],
    name: 'security/maintainer-data-tooling',
    rules: {
      'security/detect-non-literal-fs-filename': 'off',
    },
  },
  {
    // unicorn/prefer-module exists to drive ESM migration and forbids
    // __dirname/__filename, which "are not available in JavaScript modules".
    // These packages all extend the root tsconfig (module: nodenext) with no
    // "type": "module", so they COMPILE TO COMMONJS — __dirname is correct
    // there and import.meta is a syntax error. The rule is also auto-fixable:
    // a --fix pass would rewrite __dirname to import.meta and break the build
    // (same hazard class as sort-decorators; see
    // docs/development/eslint-config-decisions.md). Scoped off until an ESM
    // migration; the bundler-resolved frontend keeps it.
    files: [
      'apps/backend/**/*.{js,cjs,ts,cts}',
      'libs/**/*.{js,cjs,ts,cts}',
    ],
    name: 'unicorn/cjs-compile-target',
    rules: { 'unicorn/prefer-module': 'off' },
  },
  {
    // eslint-plugin-n models NODE.JS runtime resolution. apps/frontend is a
    // webpack-bundled Vue app whose `@/*` imports are resolved by the BUNDLER
    // via tsconfig paths — Node never resolves them, so the rule reports 326
    // failures for imports that are correct. `settings.n.tsconfigPath` does not
    // teach it those aliases (verified: relative and absolute both still fail).
    // import-x/no-unresolved covers the same ground and, with the resolver
    // configured above, reports them correctly — so this is redundant here,
    // not merely inconvenient. The backend IS a Node app and keeps the rule.
    files: ['apps/frontend/**/*.{js,mjs,cjs,ts,mts,cts,vue}'],
    name: 'n/frontend-bundler-resolution',
    rules: { 'n/no-missing-import': 'off' },
  },
  {
    extends: [json.configs.recommended],
    files: ['**/*.json'],
    ignores: ['package-lock.json', 'parse_testbed/**', 'schemas/**'],
    language: 'json/json',
    name: 'json',
  },
  {
    // VS Code config files are JSONC — comments are part of the format. The
    // strict json language fatals on the first `//` ("Unexpected character
    // '/'"), which silently un-linted .vscode/. This files/language pairing is
    // @eslint/json's own documented example for exactly these files.
    extends: [json.configs.recommended],
    files: ['**/*.jsonc', '.vscode/*.json'],
    language: 'json/jsonc',
    name: 'jsonc',
    plugins: { json },
  },
  {
    extends: [{ ...e18e.configs.moduleReplacements, name: 'e18e/moduleReplacements' }],
    files: ['**/package.json'],
    language: 'json/json',
    name: 'package.json',
    plugins: { json },
    rules: {
      // Dependency migrations (axios→fetch, lodash→native, moment→dayjs,
      // jsonwebtoken→jose, uuid/rimraf/dotenv→native) are engineering
      // projects, not lint fixes. Captured as the dependency-modernization
      // epic on the board; rule returns when that epic is worked
      // (2026-08-13 triage, Aaron).
      'e18e/ban-dependencies': 'off',
    },
  },
  {
    extends: [
      markdown.configs.recommended,
      markdownLinks.configs.recommended,
      markdownPreferences.configs.standard,
    ],
    files: ['**/*.md'],
    // UPSTREAM BUG WORKAROUND (2026-08-12). @eslint/markdown 8.0.2 on ESLint
    // 10.5.0 throws "Custom getLoc() method must be implemented in the
    // subclass" (from @eslint/plugin-kit 0.7.2) when a GFM email autolink sits
    // inside UNDERSCORE emphasis. Minimal reproduction:
    //     _a@b.com_      -> crash
    //     *a@b.com*      -> fine
    //     **a@b.com**    -> fine
    //     a@b.com        -> fine
    //     _no-at-sign_   -> fine
    // The crash aborts the ENTIRE eslint run, not just the offending file, so a
    // single line of markdown silently disabled linting for the whole repo —
    // which is how ~56k violations accumulated unnoticed (`lint:ci` also had a
    // `|| true` that hid the non-zero exit).
    // Only one tracked file trips it: the RPM man page, at
    // `**ADMIN_EMAIL**=_admin@heimdall.local_`.
    // Remove this ignore once the upstream fix lands and @eslint/markdown is
    // bumped; verify with the five-line reproduction above.
    ignores: [
      'packaging/rpm/man/heimdall-server-backend.env.5.md',
      // Copies of external standards (MITRE SAF license text, Contributor
      // Covenant). Matching upstream BYTE-FOR-BYTE is their requirement, so
      // no markdown rule can legitimately fire on them — and fixers must
      // never rewrite them. A layout `--fix` pass converted LICENSE.md's
      // Apache URL line to a fenced block on 2026-08-13 before this ignore
      // existed; the files were restored from HEAD.
      '**/LICENSE.md',
      'CODE_OF_CONDUCT.md',
    ],
    language: 'markdown/gfm',
    name: 'markdown',
    plugins: { markdown },
    // Formatting belongs to Prettier, which formats markdown too (Aaron,
    // 2026-08-13 triage). These are markdown-preferences' pure-formatting
    // rules — the exact analogue of the @stylistic rules eslint-config-
    // prettier switches off for code, which it cannot do here because it does
    // not know this plugin. They accounted for ~800 problems, 85% in
    // packaging/. The plugin's correctness/content rules (prefer-fenced-code-
    // blocks, prefer-autolinks, link checks) stay on.
    rules: {
      'markdown-preferences/bullet-list-marker-style': 'off',
      'markdown-preferences/emphasis-delimiters-style': 'off',
      'markdown-preferences/hard-linebreak-style': 'off',
      'markdown-preferences/indent': 'off',
      'markdown-preferences/no-multi-spaces': 'off',
      'markdown-preferences/no-multiple-empty-lines': 'off',
      'markdown-preferences/no-trailing-spaces': 'off',
      'markdown-preferences/ordered-list-marker-sequence': 'off',
      'markdown-preferences/padding-line-between-blocks': 'off',
      'markdown-preferences/table-pipe-alignment': 'off',
      'markdown-preferences/table-pipe-spacing': 'off',
      // Its fixer converts RELATIVE links — [SECURITY.md](SECURITY.md) became
      // <SECURITY.md> on 2026-08-13 — but angle-bracket autolinks require an
      // absolute URI with a scheme, so the output is not a link at all;
      // renderers treat it as a raw HTML tag. A fixer that produces invalid
      // markdown from valid markdown cannot be trusted on any file.
      'markdown-preferences/prefer-autolinks': 'off',
    },
  },
  // MUST BE LAST. eslint-config-prettier only turns rules OFF — every
  // formatting rule that would fight the formatter — so anything placed after
  // it would switch those rules back on and reintroduce the conflict.
  // Per Prettier's own guidance: formatting belongs to the formatter, code
  // quality to the linter, and the two run as separate tools.
  // eslint-plugin-prettier (Prettier AS an ESLint rule) is deliberately NOT
  // used — Prettier documents it as discouraged: slower, and it reports
  // formatting as lint errors, which is exactly the noise this removes.
  eslintConfigPrettier,
]);
//     Should we retain this naming convention for any (i.e. common, hdf-converters projects) / all interfaces (soon to be mostly all types)
//     "@typescript-eslint/naming-convention": [
//       "warn",
//       {
//         "selector": "interface",
//         "format": ["PascalCase"],
//         "custom": {
//           "regex": "^I[A-Z]",
//           "match": true
//         }
//       }
//     ],
//
//     --
//
//     backend sequelize migrations probably should be linted before merge but not modified afterwards, not sure how to implement that atm but it seems like between the tsconfig and allowdefaultproject setting they're being ignored for now
