/* eslint-disable n/no-extraneous-import */

import e18e from '@e18e/eslint-plugin';
import comments from '@eslint-community/eslint-plugin-eslint-comments/configs';
import js from '@eslint/js';
import json from '@eslint/json';
import markdown from '@eslint/markdown';
import stylistic from '@stylistic/eslint-plugin';
import vitest from '@vitest/eslint-plugin';
import eslintConfigPrettier from 'eslint-config-prettier/flat';
import {
  createTypeScriptImportResolver,
  defaultExtensions,
} from 'eslint-import-resolver-typescript';
import { importX } from 'eslint-plugin-import-x';
import markdownLinks from 'eslint-plugin-markdown-links';
import markdownPreferences from 'eslint-plugin-markdown-preferences';
import n from 'eslint-plugin-n';
import promise from 'eslint-plugin-promise';
import regexp from 'eslint-plugin-regexp';
import security from 'eslint-plugin-security';
import unicorn from 'eslint-plugin-unicorn';
import yml from 'eslint-plugin-yml';
import { defineConfig } from 'eslint/config';
import tseslint from 'typescript-eslint';
import cypress from 'eslint-plugin-cypress';
import vue from 'eslint-plugin-vue';

/* eslint-enable n/no-extraneous-import */

export default defineConfig([
  {
    // `docs` is the VitePress documentation site (ADR-005 §2.1): an isolated
    // project with its own package.json, lockfile and toolchain, deliberately
    // outside the workspaces globs. This config's typed linting cannot parse
    // its .vitepress sources (they belong to no tsconfig project), and its
    // markdown answers to the docs build — `yarn build` inside docs/, with
    // dead-link checking — not to the application's markdown rules.
    ignores: [
      '**/dist',
      '**/lib',
      '**/node_modules',
      'libs/inspecjs/src/generated_parsers/**',
      'docs/**',
      // Static DATA tables and generated sources — extending the
      // generated_parsers precedent directly above. These hold no logic, so
      // linting them yields no correctness signal (TypeScript still type-checks
      // them); what it did yield was 36k formatting complaints that buried the
      // real findings. NiktoNistMappingData.ts alone produced 26,836 messages —
      // 17,882 "use single quotes" and 8,941 "don't quote props", i.e. exactly
      // 3 per data row. Scoped to the *MappingData.ts suffix on purpose: the
      // sibling *Mapping.ts / *MappingItem.ts files ARE logic and stay linted.
      '**/*MappingData.ts',
      'libs/hdf-converters/src/ckl-mapper/jsonixMapping.ts', // "Generated by jsonix-schema-compiler"
      'apps/frontend/src/utilities/cci_util.ts', // 14k-line CCI_DESCRIPTIONS table, zero functions
    ],
    name: 'global ignores',
  },
  {
    extends: [
      js.configs.recommended,
      tseslint.configs.recommendedTypeChecked,
      vitest.configs.recommended,
      promise.configs['flat/recommended'],
      { ...regexp.configs.all, name: 'regexp/all' },
      unicorn.configs.recommended,
      n.configs['flat/recommended'],
      {
        ...stylistic.configs.customize({
          braceStyle: '1tbs',
          indent: [2, { SwitchCase: 1 }],
          quoteProps: 'as-needed',
          quotes: 'single',
          semi: true,
        }), name: '@stylistic/customized',
      },
      tseslint.configs.stylisticTypeChecked,
      comments.recommended,
      yml.configs.standard.map((cfg) => ({...cfg, name: 'yml/standard'})),
      security.configs.recommended,
      importX.flatConfigs.recommended,
      importX.flatConfigs.typescript,
      // perfectionist's preset is deliberately NOT extended. Its sort-* rules
      // carry zero correctness value and every one is a `suggestion`-type
      // autofix — the AST-rewriting class ESLint's own docs say must not be
      // auto-applied when "a fix potentially changes functionality". In this
      // repo they did exactly that: sort-decorators reordered sequelize
      // decorators and the whole backend suite stopped collecting;
      // sort-classes landed in an unsatisfiable conflict with
      // unicorn/consistent-class-member-order; sort-objects reordering object
      // literals contributed to a typing break in evaluations.service.ts.
      // sort-objects is also unsound in principle — key order is semantic
      // across a spread ({...defaults, mode} !== {mode, ...defaults}).
      // The import-ordering rules were kept at first, then dropped too:
      // sort-imports MOVES side-effect imports, which are order-dependent.
      // Verified by dry run — it relocated `import '@mdi/font/...css'` behind
      // the vuetify import in plugins/vuetify.ts, reordering the CSS cascade,
      // and ControlRowDetails.vue has five prismjs imports where the core must
      // load before its language components register onto it. No sort-* rule
      // here can reach zero without rewriting order that carries meaning.
      { ...e18e.configs.modernization, name: 'e18e/modernization' },
      { ...e18e.configs.performanceImprovements, name: 'e18e/performanceImprovements' },
      cypress.configs.recommended,
      vue.configs['flat/vue2-recommended'],
    ],
    files: ['**/*.{js,mjs,cjs,ts,mts,cts,vue}'],
    languageOptions: {
      ecmaVersion: 'latest',
      parserOptions: { 
        extraFileExtensions: ['.vue'],
        parser: tseslint.parser,
        projectService: { 
          allowDefaultProject: [
            'apps/frontend/vue.config.js',
            'eslint.config.mjs',
            'libs/password-complexity/index.js',
            'vitest.config.ts',
          ]
        }
      },
      sourceType: 'module',
    },
    name: 'js/ts',
    rules: {
      '@stylistic/eol-last': 'error',
      '@stylistic/object-curly-newline': ['error', { multiline: true }],
      '@stylistic/quotes': ['error', 'single', { avoidEscape: true }],
      '@typescript-eslint/consistent-type-definitions': ['error', 'type'],
      '@typescript-eslint/consistent-type-exports': 'error',
      '@typescript-eslint/consistent-type-imports': 'error',
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-redundant-type-constituents': 'off',
      '@typescript-eslint/no-unsafe-argument': 'off',
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-call': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-return': 'off',
      '@typescript-eslint/prefer-nullish-coalescing': 'off',
      curly: 'error',
      'n/no-missing-import': ['error', { tryExtensions: ['.ts', '.tsx', '.d.ts', '.js', '.jsx', '.mjs', '.cjs', '.json'] }],
      'prefer-object-has-own': 'error',
      'unicorn/filename-case': ['error', { case: 'snakeCase' }],
      'unicorn/no-null': 'off',
      'unicorn/no-process-exit': 'off',
      'unicorn/prefer-node-protocol': 'off',
      'unicorn/prevent-abbreviations': 'off',
    },
    // Without this, import-x/n resolve imports from the REPO ROOT and never see
    // apps/frontend/tsconfig.json, where `@/*` -> `./src/*` is defined. Every
    // `@/...` import in the frontend then reports as unresolved — ~744 errors
    // for imports that resolve correctly in every real build. Listing each
    // package's tsconfig lets the resolver pick the one closest to the file
    // being linted (see the resolver's affinity sorting).
    settings: {
      // lodash is CommonJS and builds its export object dynamically, so
      // import-x cannot statically enumerate its members. With 62 files doing
      // `import * as _ from 'lodash'`, import-x/namespace reported 797 errors
      // of the form "'get' not found in imported namespace '_'" — for
      // functions that demonstrably exist (`typeof _.get === 'function'`).
      // Every one was a false positive. This is the rule's documented escape
      // hatch for modules whose exports can't be analyzed; it is scoped to
      // lodash, so namespace checking stays active for every other module.
      'import-x/ignore': ['lodash'],
      'import-x/resolver-next': [
        createTypeScriptImportResolver({
          extensions: [...defaultExtensions, '.vue'],
          noWarnOnMultipleProjects: true,
          project: [
            'tsconfig.json',
            'apps/*/tsconfig.json',
            'libs/*/tsconfig.json',
            'test/tsconfig.json',
          ],
        }),
      ],
    },
  },
  {
    // eslint-plugin-n models NODE.JS runtime resolution. apps/frontend is a
    // webpack-bundled Vue app whose `@/*` imports are resolved by the BUNDLER
    // via tsconfig paths — Node never resolves them, so the rule reports 326
    // failures for imports that are correct. `settings.n.tsconfigPath` does not
    // teach it those aliases (verified: relative and absolute both still fail).
    // import-x/no-unresolved covers the same ground and, with the resolver
    // configured above, reports them correctly — so this is redundant here,
    // not merely inconvenient. The backend IS a Node app and keeps the rule.
    files: ['apps/frontend/**/*.{js,mjs,cjs,ts,mts,cts,vue}'],
    name: 'n/frontend-bundler-resolution',
    rules: { 'n/no-missing-import': 'off' },
  },
  {
    extends: [json.configs.recommended],
    files: ['**/*.json'],
    ignores: ['package-lock.json', 'parse_testbed/**', 'schemas/**'],
    language: 'json/json',
    name: 'json',
    plugins: { json },
  },
  {
    extends: [{ ...e18e.configs.moduleReplacements, name: 'e18e/moduleReplacements' }],
    files: ['**/package.json'],
    language: 'json/json',
    name: 'package.json',
    plugins: { json },
  },
  {
    extends: [
      markdown.configs.recommended,
      markdownLinks.configs.recommended,
      markdownPreferences.configs.standard,
    ],
    files: ['**/*.md'],
    // UPSTREAM BUG WORKAROUND (2026-08-12). @eslint/markdown 8.0.2 on ESLint
    // 10.5.0 throws "Custom getLoc() method must be implemented in the
    // subclass" (from @eslint/plugin-kit 0.7.2) when a GFM email autolink sits
    // inside UNDERSCORE emphasis. Minimal reproduction:
    //     _a@b.com_      -> crash
    //     *a@b.com*      -> fine
    //     **a@b.com**    -> fine
    //     a@b.com        -> fine
    //     _no-at-sign_   -> fine
    // The crash aborts the ENTIRE eslint run, not just the offending file, so a
    // single line of markdown silently disabled linting for the whole repo —
    // which is how ~56k violations accumulated unnoticed (`lint:ci` also had a
    // `|| true` that hid the non-zero exit).
    // Only one tracked file trips it: the RPM man page, at
    // `**ADMIN_EMAIL**=_admin@heimdall.local_`.
    // Remove this ignore once the upstream fix lands and @eslint/markdown is
    // bumped; verify with the five-line reproduction above.
    ignores: ['packaging/rpm/man/heimdall-server-backend.env.5.md'],
    language: 'markdown/gfm',
    name: 'markdown',
    plugins: { markdown },
  },
  // MUST BE LAST. eslint-config-prettier only turns rules OFF — every
  // formatting rule that would fight the formatter — so anything placed after
  // it would switch those rules back on and reintroduce the conflict.
  // Per Prettier's own guidance: formatting belongs to the formatter, code
  // quality to the linter, and the two run as separate tools.
  // eslint-plugin-prettier (Prettier AS an ESLint rule) is deliberately NOT
  // used — Prettier documents it as discouraged: slower, and it reports
  // formatting as lint errors, which is exactly the noise this removes.
  eslintConfigPrettier,
]);
//     Should we retain this naming convention for any (i.e. common, hdf-converters projects) / all interfaces (soon to be mostly all types)
//     "@typescript-eslint/naming-convention": [
//       "warn",
//       {
//         "selector": "interface",
//         "format": ["PascalCase"],
//         "custom": {
//           "regex": "^I[A-Z]",
//           "match": true
//         }
//       }
//     ],
//
//     --
//
//     backend sequelize migrations probably should be linted before merge but not modified afterwards, not sure how to implement that atm but it seems like between the tsconfig and allowdefaultproject setting they're being ignored for now
