export const data = [
  {
    AwsConfigRuleName: 'secretsmanager-scheduled-rotation-success-check',
    AwsConfigRuleSourceIdentifier:
      'SECRETSMANAGER_SCHEDULED_ROTATION_SUCCESS_CHECK',
    'NIST-ID': 'AC-2(1)|AC-2(j)',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'iam-user-group-membership-check',
    AwsConfigRuleSourceIdentifier: 'IAM_USER_GROUP_MEMBERSHIP_CHECK',
    'NIST-ID': 'AC-2(1)|AC-2(j)|AC-3|AC-6',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'iam-password-policy',
    AwsConfigRuleSourceIdentifier: 'IAM_PASSWORD_POLICY',
    'NIST-ID': 'AC-2(1)|AC-2(f)|AC-2(j)|IA-2|IA-5(1)(a)(d)(e)|IA-5(4)',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'access-keys-rotated',
    AwsConfigRuleSourceIdentifier: 'ACCESS_KEYS_ROTATED',
    'NIST-ID': 'AC-2(1)|AC-2(j)',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'iam-user-unused-credentials-check',
    AwsConfigRuleSourceIdentifier: 'IAM_USER_UNUSED_CREDENTIALS_CHECK',
    'NIST-ID': 'AC-2(1)|AC-2(3)|AC-2(f)|AC-3|AC-6',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'securityhub-enabled',
    AwsConfigRuleSourceIdentifier: 'SECURITYHUB_ENABLED',
    'NIST-ID':
      'AC-2(1)|AC-2(4)|AC-2(12)(a)|AC-2(g)|AC-17(1)|AU-6(1)(3)|CA-7(a)(b)|SA-10|SI-4(2)|SI-4(4)|SI-4(5)|SI-4(16)|SI-4(a)(b)(c)',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'guardduty-enabled-centralized',
    AwsConfigRuleSourceIdentifier: 'GUARDDUTY_ENABLED_CENTRALIZED',
    'NIST-ID':
      'AC-2(1)|AC-2(4)|AC-2(12)(a)|AC-2(g)|AC-17(1)|AU-6(1)(3)|CA-7(a)(b)|RA-5|SA-10|SI-4(1)|SI-4(2)|SI-4(4)|SI-4(5)|SI-4(16)|SI-4(a)(b)(c)',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'cloud-trail-cloud-watch-logs-enabled',
    AwsConfigRuleSourceIdentifier: 'CLOUD_TRAIL_CLOUD_WATCH_LOGS_ENABLED',
    'NIST-ID':
      'AC-2(4)|AC-2(g)|AU-2(a)(d)|AU-3|AU-6(1)(3)|AU-7(1)|AU-12(a)(c)|CA-7(a)(b)|SI-4(2)|SI-4(4)|SI-4(5)|SI-4(a)(b)(c)',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'cloudtrail-enabled',
    AwsConfigRuleSourceIdentifier: 'CLOUD_TRAIL_ENABLED',
    'NIST-ID': 'AC-2(4)|AC-2(g)|AU-2(a)(d)|AU-3|AU-12(a)(c)',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'multi-region-cloudtrail-enabled',
    AwsConfigRuleSourceIdentifier: 'MULTI_REGION_CLOUD_TRAIL_ENABLED',
    'NIST-ID': 'AC-2(4)|AU-2(a)(d)|AU-3|AU-12(a)(c)',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'rds-logging-enabled',
    AwsConfigRuleSourceIdentifier: 'RDS_LOGGING_ENABLED',
    'NIST-ID': 'AC-2(4)|AC-2(g)|AU-2(a)(d)|AU-3|AU-12(a)(c)',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'cloudwatch-alarm-action-check',
    AwsConfigRuleSourceIdentifier: 'CLOUDWATCH_ALARM_ACTION_CHECK',
    'NIST-ID':
      'AC-2(4)|AU-6(1)(3)|AU-7(1)|CA-7(a)(b)|IR-4(1)|SI-4(2)|SI-4(4)|SI-4(5)|SI-4(a)(b)(c)',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'redshift-cluster-configuration-check',
    AwsConfigRuleSourceIdentifier: 'REDSHIFT_CLUSTER_CONFIGURATION_CHECK',
    'NIST-ID': 'AC-2(4)|AC-2(g)|AU-2(a)(d)|AU-3|AU-12(a)(c)|SC-13|SC-28',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'iam-root-access-key-check',
    AwsConfigRuleSourceIdentifier: 'IAM_ROOT_ACCESS_KEY_CHECK',
    'NIST-ID': 'AC-2(f)|AC-2(j)|AC-3|AC-6|AC-6(10)',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 's3-bucket-logging-enabled',
    AwsConfigRuleSourceIdentifier: 'S3_BUCKET_LOGGING_ENABLED',
    'NIST-ID': 'AC-2(g)|AU-2(a)(d)|AU-3|AU-12(a)(c)',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'cloudtrail-s3-dataevents-enabled',
    AwsConfigRuleSourceIdentifier: 'CLOUDTRAIL_S3_DATAEVENTS_ENABLED',
    'NIST-ID': 'AC-2(g)|AU-2(a)(d)|AU-3|AU-12(a)(c)',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'root-account-mfa-enabled',
    AwsConfigRuleSourceIdentifier: 'ROOT_ACCOUNT_MFA_ENABLED',
    'NIST-ID': 'AC-2(j)|IA-2(1)(11)',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'emr-kerberos-enabled',
    AwsConfigRuleSourceIdentifier: 'EMR_KERBEROS_ENABLED',
    'NIST-ID': 'AC-2(j)|AC-3|AC-5(c)|AC-6',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'iam-group-has-users-check',
    AwsConfigRuleSourceIdentifier: 'IAM_GROUP_HAS_USERS_CHECK',
    'NIST-ID': 'AC-2(j)|AC-3|AC-5(c)|AC-6|SC-2',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'iam-policy-no-statements-with-admin-access',
    AwsConfigRuleSourceIdentifier: 'IAM_POLICY_NO_STATEMENTS_WITH_ADMIN_ACCESS',
    'NIST-ID': 'AC-2(j)|AC-3|AC-5(c)|AC-6|SC-2',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'iam-user-no-policies-check',
    AwsConfigRuleSourceIdentifier: 'IAM_USER_NO_POLICIES_CHECK',
    'NIST-ID': 'AC-2(j)|AC-3|AC-5(c)|AC-6',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 's3-bucket-public-write-prohibited',
    AwsConfigRuleSourceIdentifier: 'S3_BUCKET_PUBLIC_WRITE_PROHIBITED',
    'NIST-ID': 'AC-3|AC-4|AC-6|AC-21(b)|SC-7|SC-7(3)',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'lambda-function-public-access-prohibited',
    AwsConfigRuleSourceIdentifier: 'LAMBDA_FUNCTION_PUBLIC_ACCESS_PROHIBITED',
    'NIST-ID': 'AC-3|AC-4|AC-6|AC-21(b)|SC-7|SC-7(3)',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'rds-snapshots-public-prohibited',
    AwsConfigRuleSourceIdentifier: 'RDS_SNAPSHOTS_PUBLIC_PROHIBITED',
    'NIST-ID': 'AC-3|AC-4|AC-6|AC-21(b)|SC-7|SC-7(3)',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'redshift-cluster-public-access-check',
    AwsConfigRuleSourceIdentifier: 'REDSHIFT_CLUSTER_PUBLIC_ACCESS_CHECK',
    'NIST-ID': 'AC-3|AC-4|AC-6|AC-21(b)|SC-7|SC-7(3)',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 's3-bucket-policy-grantee-check',
    AwsConfigRuleSourceIdentifier: 'S3_BUCKET_POLICY_GRANTEE_CHECK',
    'NIST-ID': 'AC-3|AC-6|SC-7|SC-7(3)',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 's3-bucket-public-read-prohibited',
    AwsConfigRuleSourceIdentifier: 'S3_BUCKET_PUBLIC_READ_PROHIBITED',
    'NIST-ID': 'AC-3|AC-4|AC-6|AC-21(b)|SC-7|SC-7(3)',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 's3-account-level-public-access-blocks',
    AwsConfigRuleSourceIdentifier: 'S3_ACCOUNT_LEVEL_PUBLIC_ACCESS_BLOCKS',
    'NIST-ID': 'AC-3|AC-4|AC-6|AC-21(b)|SC-7|SC-7(3)',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'dms-replication-not-public',
    AwsConfigRuleSourceIdentifier: 'DMS_REPLICATION_NOT_PUBLIC',
    'NIST-ID': 'AC-3|AC-4|AC-6|AC-21(b)|SC-7|SC-7(3)',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'ebs-snapshot-public-restorable-check',
    AwsConfigRuleSourceIdentifier: 'EBS_SNAPSHOT_PUBLIC_RESTORABLE_CHECK',
    'NIST-ID': 'AC-3|AC-4|AC-6|AC-21(b)|SC-7|SC-7(3)',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'sagemaker-notebook-no-direct-internet-access',
    AwsConfigRuleSourceIdentifier:
      'SAGEMAKER_NOTEBOOK_NO_DIRECT_INTERNET_ACCESS',
    'NIST-ID': 'AC-3|AC-4|AC-6|AC-21(b)|SC-7|SC-7(3)',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'rds-instance-public-access-check',
    AwsConfigRuleSourceIdentifier: 'RDS_INSTANCE_PUBLIC_ACCESS_CHECK',
    'NIST-ID': 'AC-4|AC-6|AC-21(b)|SC-7|SC-7(3)',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'lambda-inside-vpc',
    AwsConfigRuleSourceIdentifier: 'LAMBDA_INSIDE_VPC',
    'NIST-ID': 'AC-4|SC-7|SC-7(3)',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'ec2-instances-in-vpc',
    AwsConfigRuleSourceIdentifier: 'INSTANCES_IN_VPC',
    'NIST-ID': 'AC-4|SC-7|SC-7(3)',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'restricted-common-ports',
    AwsConfigRuleSourceIdentifier: 'RESTRICTED_INCOMING_TRAFFIC',
    'NIST-ID': 'AC-4|CM-2|SC-7|SC-7(3)',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'restricted-ssh',
    AwsConfigRuleSourceIdentifier: 'INCOMING_SSH_DISABLED',
    'NIST-ID': 'AC-4|SC-7|SC-7(3)',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'vpc-default-security-group-closed',
    AwsConfigRuleSourceIdentifier: 'VPC_DEFAULT_SECURITY_GROUP_CLOSED',
    'NIST-ID': 'AC-4|SC-7|SC-7(3)',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'vpc-sg-open-only-to-authorized-ports',
    AwsConfigRuleSourceIdentifier: 'VPC_SG_OPEN_ONLY_TO_AUTHORIZED_PORTS',
    'NIST-ID': 'AC-4|SC-7|SC-7(3)',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'acm-certificate-expiration-check',
    AwsConfigRuleSourceIdentifier: 'ACM_CERTIFICATE_EXPIRATION_CHECK',
    'NIST-ID': 'AC-4|AC-17(2)|SC-12',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'ec2-instance-no-public-ip',
    AwsConfigRuleSourceIdentifier: 'EC2_INSTANCE_NO_PUBLIC_IP',
    'NIST-ID': 'AC-4|AC-6|AC-21(b)|SC-7|SC-7(3)',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'elasticsearch-in-vpc-only',
    AwsConfigRuleSourceIdentifier: 'ELASTICSEARCH_IN_VPC_ONLY',
    'NIST-ID': 'AC-4|SC-7|SC-7(3)',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'emr-master-no-public-ip',
    AwsConfigRuleSourceIdentifier: 'EMR_MASTER_NO_PUBLIC_IP',
    'NIST-ID': 'AC-4|AC-21(b)|SC-7|SC-7(3)',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'internet-gateway-authorized-vpc-only',
    AwsConfigRuleSourceIdentifier: 'INTERNET_GATEWAY_AUTHORIZED_VPC_ONLY',
    'NIST-ID': 'AC-4|AC-17(3)|SC-7|SC-7(3)',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'codebuild-project-envvar-awscred-check',
    AwsConfigRuleSourceIdentifier: 'CODEBUILD_PROJECT_ENVVAR_AWSCRED_CHECK',
    'NIST-ID': 'AC-6|IA-5(7)|SA-3(a)',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'ec2-imdsv2-check',
    AwsConfigRuleSourceIdentifier: 'EC2_IMDSV2_CHECK',
    'NIST-ID': 'AC-6',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'iam-no-inline-policy-check',
    AwsConfigRuleSourceIdentifier: 'IAM_NO_INLINE_POLICY_CHECK',
    'NIST-ID': 'AC-6',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'alb-http-to-https-redirection-check',
    AwsConfigRuleSourceIdentifier: 'ALB_HTTP_TO_HTTPS_REDIRECTION_CHECK',
    'NIST-ID': 'AC-17(2)|SC-7|SC-8|SC-8(1)|SC-13|SC-23',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'redshift-require-tls-ssl',
    AwsConfigRuleSourceIdentifier: 'REDSHIFT_REQUIRE_TLS_SSL',
    'NIST-ID': 'AC-17(2)|SC-7|SC-8|SC-8(1)|SC-13',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 's3-bucket-ssl-requests-only',
    AwsConfigRuleSourceIdentifier: 'S3_BUCKET_SSL_REQUESTS_ONLY',
    'NIST-ID': 'AC-17(2)|SC-7|SC-8|SC-8(1)|SC-13',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'elb-acm-certificate-required',
    AwsConfigRuleSourceIdentifier: 'ELB_ACM_CERTIFICATE_REQUIRED',
    'NIST-ID': 'AC-17(2)|SC-7|SC-8|SC-8(1)|SC-13',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'alb-http-drop-invalid-header-enabled',
    AwsConfigRuleSourceIdentifier: 'ALB_HTTP_DROP_INVALID_HEADER_ENABLED',
    'NIST-ID': 'AC-17(2)|SC-7|SC-8|SC-8(1)|SC-23',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'elb-tls-https-listeners-only',
    AwsConfigRuleSourceIdentifier: 'ELB_TLS_HTTPS_LISTENERS_ONLY',
    'NIST-ID': 'AC-17(2)|SC-7|SC-8|SC-8(1)|SC-23',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'api-gw-execution-logging-enabled',
    AwsConfigRuleSourceIdentifier: 'API_GW_EXECUTION_LOGGING_ENABLED',
    'NIST-ID': 'AU-2(a)(d)|AU-3|AU-12(a)(c)',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'elb-logging-enabled',
    AwsConfigRuleSourceIdentifier: 'ELB_LOGGING_ENABLED',
    'NIST-ID': 'AU-2(a)(d)|AU-3|AU-12(a)(c)',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'vpc-flow-logs-enabled',
    AwsConfigRuleSourceIdentifier: 'VPC_FLOW_LOGS_ENABLED',
    'NIST-ID': 'AU-2(a)(d)|AU-3|AU-12(a)(c)',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'wafv2-logging-enabled',
    AwsConfigRuleSourceIdentifier: 'WAFV2_LOGGING_ENABLED',
    'NIST-ID': 'AU-2(a)(d)|AU-3|AU-12(a)(c)|SC-7|SI-4(a)(b)(c)',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'cloud-trail-encryption-enabled',
    AwsConfigRuleSourceIdentifier: 'CLOUD_TRAIL_ENCRYPTION_ENABLED',
    'NIST-ID': 'AU-9|SC-13|SC-28',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'cloudwatch-log-group-encrypted',
    AwsConfigRuleSourceIdentifier: 'CLOUDWATCH_LOG_GROUP_ENCRYPTED',
    'NIST-ID': 'AU-9|SC-13|SC-28',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 's3-bucket-replication-enabled',
    AwsConfigRuleSourceIdentifier: 'S3_BUCKET_REPLICATION_ENABLED',
    'NIST-ID': 'AU-9(2)|CP-9(b)|CP-10|SC-5|SC-36',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'cw-loggroup-retention-period-check',
    AwsConfigRuleSourceIdentifier: 'CW_LOGGROUP_RETENTION_PERIOD_CHECK',
    'NIST-ID': 'AU-11|SI-12',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'ec2-instance-detailed-monitoring-enabled',
    AwsConfigRuleSourceIdentifier: 'EC2_INSTANCE_DETAILED_MONITORING_ENABLED',
    'NIST-ID': 'CA-7(a)(b)|SI-4(2)|SI-4(a)(b)(c)',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'rds-enhanced-monitoring-enabled',
    AwsConfigRuleSourceIdentifier: 'RDS_ENHANCED_MONITORING_ENABLED',
    'NIST-ID': 'CA-7(a)(b)',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'ec2-instance-managed-by-systems-manager',
    AwsConfigRuleSourceIdentifier: 'EC2_INSTANCE_MANAGED_BY_SSM',
    'NIST-ID': 'CM-2|CM-7(a)|CM-8(1)|CM-8(3)(a)|SA-3(a)|SA-10|SI-2(2)|SI-7(1)',
    Rev: 4,
  },
  {
    AwsConfigRuleName:
      'ec2-managedinstance-association-compliance-status-check',
    AwsConfigRuleSourceIdentifier:
      'EC2_MANAGEDINSTANCE_ASSOCIATION_COMPLIANCE_STATUS_CHECK',
    'NIST-ID': 'CM-2|CM-7(a)|CM-8(3)(a)|SI-2(2)',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'ec2-stopped-instance',
    AwsConfigRuleSourceIdentifier: 'EC2_STOPPED_INSTANCE',
    'NIST-ID': 'CM-2',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'ec2-volume-inuse-check',
    AwsConfigRuleSourceIdentifier: 'EC2_VOLUME_INUSE_CHECK',
    'NIST-ID': 'CM-2|SC-4',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'elb-deletion-protection-enabled',
    AwsConfigRuleSourceIdentifier: 'ELB_DELETION_PROTECTION_ENABLED',
    'NIST-ID': 'CM-2|CP-10',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'cloudtrail-security-trail-enabled',
    AwsConfigRuleSourceIdentifier: 'CLOUDTRAIL_SECURITY_TRAIL_ENABLED',
    'NIST-ID': 'CM-2',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'ec2-managedinstance-patch-compliance-status-check',
    AwsConfigRuleSourceIdentifier:
      'EC2_MANAGEDINSTANCE_PATCH_COMPLIANCE_STATUS_CHECK',
    'NIST-ID': 'CM-8(3)(a)|SI-2(2)|SI-7(1)',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'db-instance-backup-enabled',
    AwsConfigRuleSourceIdentifier: 'DB_INSTANCE_BACKUP_ENABLED',
    'NIST-ID': 'CP-9(b)|CP-10|SI-12',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'dynamodb-pitr-enabled',
    AwsConfigRuleSourceIdentifier: 'DYNAMODB_PITR_ENABLED',
    'NIST-ID': 'CP-9(b)|CP-10|SI-12',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'elasticache-redis-cluster-automatic-backup-check',
    AwsConfigRuleSourceIdentifier:
      'ELASTICACHE_REDIS_CLUSTER_AUTOMATIC_BACKUP_CHECK',
    'NIST-ID': 'CP-9(b)|CP-10|SI-12',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'dynamodb-in-backup-plan',
    AwsConfigRuleSourceIdentifier: 'DYNAMODB_IN_BACKUP_PLAN',
    'NIST-ID': 'CP-9(b)|CP-10|SI-12',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'ebs-in-backup-plan',
    AwsConfigRuleSourceIdentifier: 'EBS_IN_BACKUP_PLAN',
    'NIST-ID': 'CP-9(b)|CP-10|SI-12',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'efs-in-backup-plan',
    AwsConfigRuleSourceIdentifier: 'EFS_IN_BACKUP_PLAN',
    'NIST-ID': 'CP-9(b)|CP-10|SI-12',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'rds-in-backup-plan',
    AwsConfigRuleSourceIdentifier: 'RDS_IN_BACKUP_PLAN',
    'NIST-ID': 'CP-9(b)|CP-10|SI-12',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'dynamodb-autoscaling-enabled',
    AwsConfigRuleSourceIdentifier: 'DYNAMODB_AUTOSCALING_ENABLED',
    'NIST-ID': 'CP-10|SC-5',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'rds-multi-az-support',
    AwsConfigRuleSourceIdentifier: 'RDS_MULTI_AZ_SUPPORT',
    'NIST-ID': 'CP-10|SC-5|SC-36',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 's3-bucket-versioning-enabled',
    AwsConfigRuleSourceIdentifier: 'S3_BUCKET_VERSIONING_ENABLED',
    'NIST-ID': 'CP-10|SI-12',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'vpc-vpn-2-tunnels-up',
    AwsConfigRuleSourceIdentifier: 'VPC_VPN_2_TUNNELS_UP',
    'NIST-ID': 'CP-10',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'elb-cross-zone-load-balancing-enabled',
    AwsConfigRuleSourceIdentifier: 'ELB_CROSS_ZONE_LOAD_BALANCING_ENABLED',
    'NIST-ID': 'CP-10|SC-5',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'root-account-hardware-mfa-enabled',
    AwsConfigRuleSourceIdentifier: 'ROOT_ACCOUNT_HARDWARE_MFA_ENABLED',
    'NIST-ID': 'IA-2(1)(11)',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'mfa-enabled-for-iam-console-access',
    AwsConfigRuleSourceIdentifier: 'MFA_ENABLED_FOR_IAM_CONSOLE_ACCESS',
    'NIST-ID': 'IA-2(1)(2)(11)',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'iam-user-mfa-enabled',
    AwsConfigRuleSourceIdentifier: 'IAM_USER_MFA_ENABLED',
    'NIST-ID': 'IA-2(1)(2)(11)',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'guardduty-non-archived-findings',
    AwsConfigRuleSourceIdentifier: 'GUARDDUTY_NON_ARCHIVED_FINDINGS',
    'NIST-ID': 'IR-4(1)|IR-6(1)|IR-7(1)|RA-5|SA-10|SI-4(a)(b)(c)',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'codebuild-project-source-repo-url-check',
    AwsConfigRuleSourceIdentifier: 'CODEBUILD_PROJECT_SOURCE_REPO_URL_CHECK',
    'NIST-ID': 'SA-3(a)',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'autoscaling-group-elb-healthcheck-required',
    AwsConfigRuleSourceIdentifier: 'AUTOSCALING_GROUP_ELB_HEALTHCHECK_REQUIRED',
    'NIST-ID': 'SC-5',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'rds-instance-deletion-protection-enabled',
    AwsConfigRuleSourceIdentifier: 'RDS_INSTANCE_DELETION_PROTECTION_ENABLED',
    'NIST-ID': 'SC-5',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'alb-waf-enabled',
    AwsConfigRuleSourceIdentifier: 'ALB_WAF_ENABLED',
    'NIST-ID': 'SC-7|SI-4(a)(b)(c)',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'elasticsearch-node-to-node-encryption-check',
    AwsConfigRuleSourceIdentifier:
      'ELASTICSEARCH_NODE_TO_NODE_ENCRYPTION_CHECK',
    'NIST-ID': 'SC-7|SC-8|SC-8(1)',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'cmk-backing-key-rotation-enabled',
    AwsConfigRuleSourceIdentifier: 'CMK_BACKING_KEY_ROTATION_ENABLED',
    'NIST-ID': 'SC-12',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'kms-cmk-not-scheduled-for-deletion',
    AwsConfigRuleSourceIdentifier: 'KMS_CMK_NOT_SCHEDULED_FOR_DELETION',
    'NIST-ID': 'SC-12|SC-28',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'api-gw-cache-enabled-and-encrypted',
    AwsConfigRuleSourceIdentifier: 'API_GW_CACHE_ENABLED_AND_ENCRYPTED',
    'NIST-ID': 'SC-13|SC-28',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'efs-encrypted-check',
    AwsConfigRuleSourceIdentifier: 'EFS_ENCRYPTED_CHECK',
    'NIST-ID': 'SC-13|SC-28',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'elasticsearch-encrypted-at-rest',
    AwsConfigRuleSourceIdentifier: 'ELASTICSEARCH_ENCRYPTED_AT_REST',
    'NIST-ID': 'SC-13|SC-28',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'encrypted-volumes',
    AwsConfigRuleSourceIdentifier: 'ENCRYPTED_VOLUMES',
    'NIST-ID': 'SC-13|SC-28',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'rds-storage-encrypted',
    AwsConfigRuleSourceIdentifier: 'RDS_STORAGE_ENCRYPTED',
    'NIST-ID': 'SC-13|SC-28',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 's3-bucket-server-side-encryption-enabled',
    AwsConfigRuleSourceIdentifier: 'S3_BUCKET_SERVER_SIDE_ENCRYPTION_ENABLED',
    'NIST-ID': 'SC-13|SC-28',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'sagemaker-endpoint-configuration-kms-key-configured',
    AwsConfigRuleSourceIdentifier:
      'SAGEMAKER_ENDPOINT_CONFIGURATION_KMS_KEY_CONFIGURED',
    'NIST-ID': 'SC-13|SC-28',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'sagemaker-notebook-instance-kms-key-configured',
    AwsConfigRuleSourceIdentifier:
      'SAGEMAKER_NOTEBOOK_INSTANCE_KMS_KEY_CONFIGURED',
    'NIST-ID': 'SC-13|SC-28',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'sns-encrypted-kms',
    AwsConfigRuleSourceIdentifier: 'SNS_ENCRYPTED_KMS',
    'NIST-ID': 'SC-13|SC-28',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'dynamodb-table-encrypted-kms',
    AwsConfigRuleSourceIdentifier: 'DYNAMODB_TABLE_ENCRYPTED_KMS',
    'NIST-ID': 'SC-13',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 's3-bucket-default-lock-enabled',
    AwsConfigRuleSourceIdentifier: 'S3_BUCKET_DEFAULT_LOCK_ENABLED',
    'NIST-ID': 'SC-28',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'ec2-ebs-encryption-by-default',
    AwsConfigRuleSourceIdentifier: 'EC2_EBS_ENCRYPTION_BY_DEFAULT',
    'NIST-ID': 'SC-28',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'rds-snapshot-encrypted',
    AwsConfigRuleSourceIdentifier: 'RDS_SNAPSHOT_ENCRYPTED',
    'NIST-ID': 'SC-28',
    Rev: 4,
  },
  {
    AwsConfigRuleName: 'cloud-trail-log-file-validation-enabled',
    AwsConfigRuleSourceIdentifier: 'CLOUD_TRAIL_LOG_FILE_VALIDATION_ENABLED',
    'NIST-ID': 'SI-7|SI-7(1)',
    Rev: 4,
  },
];
