export const data = [
  {
    'NIST-ID': 'SI-10',
    'NIST Name': 'Information Input Validation',
    'OWASP-ID': 'A1',
    'OWASP Name': 'Injection',
    Rev: 4,
  },
  {
    'NIST-ID': 'SC-23',
    'NIST Name': 'Session Authenticity',
    'OWASP-ID': 'A2',
    'OWASP Name': 'Broken Authentication',
    Rev: 4,
  },
  {
    'NIST-ID': 'SI-11',
    'NIST Name': 'Error Handling',
    'OWASP-ID': 'A3',
    'OWASP Name': 'Sensitive Data Exposure',
    Rev: 4,
  },
  {
    'NIST-ID': 'SI-10',
    'NIST Name': 'Information Input Validation',
    'OWASP-ID': 'A4',
    'OWASP Name': 'XML External Entities (XXE)',
    Rev: 4,
  },
  {
    'NIST-ID': 'AC-3',
    'NIST Name': 'Access Enforcement',
    'OWASP-ID': 'A5',
    'OWASP Name': 'Broken Access Control',
    Rev: 4,
  },
  {
    'NIST-ID': 'CM-6',
    'NIST Name': 'Configuration Settings',
    'OWASP-ID': 'A6',
    'OWASP Name': 'Security Misconfiguration',
    Rev: 4,
  },
  {
    'NIST-ID': 'SI-10',
    'NIST Name': 'Information Input Validation',
    'OWASP-ID': 'A7',
    'OWASP Name': 'Cross-Site Scripting (XSS)',
    Rev: 4,
  },
  {
    'NIST-ID': 'SC-23',
    'NIST Name': 'Session Authenticity',
    'OWASP-ID': 'A8',
    'OWASP Name': 'Insecure Deserialization',
    Rev: 4,
  },
  {
    'NIST-ID': 'SI-2',
    'NIST Name': 'Flaw Remediation',
    'OWASP-ID': 'A9',
    'OWASP Name': 'Using Components with Known Vulnerabilities',
    Rev: 4,
  },
  {
    'NIST-ID': 'AU-12',
    'NIST Name': 'Audit Generation',
    'OWASP-ID': 'A10',
    'OWASP Name': 'Insufficient Logging&Monitoring',
    Rev: 4,
  },
];
