/**
 * Deterministic generator for KNOWN_GOOD_VECTORS (ADR-006 §14, §2).
 *
 * A PURE module — no side effects, safe to import. It builds vectors from a
 * fixed seed list using raw node:crypto (never the app's hashPassword, which
 * must be tested AGAINST these vectors; never crypto.randomBytes, so salts are
 * fixed and regeneration is byte-for-byte identical). Regenerate src/vectors.ts:
 *
 *   yarn workspace @heimdall/password-hash-vectors gen:vectors
 *
 * The spec imports buildVectors() and asserts it equals the committed
 * KNOWN_GOOD_VECTORS, so an edit to the seeds or the encoder that is not
 * regenerated fails the build. renderVectorsModule() emits lint-clean source
 * so regeneration is idempotent.
 */
import { pbkdf2Sync } from 'node:crypto';

export type Algorithm = 'sha256' | 'sha384' | 'sha512';

export type RenderedVector = {
  readonly algorithm: Algorithm;
  readonly hash: string;
  readonly iterations: number;
  readonly label: string;
  readonly password: string;
};

type Seed = {
  readonly algorithm: Algorithm;
  readonly iterations: number;
  readonly label: string;
  readonly password: string;
};

// PBKDF2 derived-key width equals the digest width (§2). A switch (not a
// Record lookup) keeps it exhaustive over the union and free of dynamic
// object indexing.
export function digestWidth(algorithm: Algorithm): number {
  switch (algorithm) {
    case 'sha256': {
      return 32;
    }
    case 'sha384': {
      return 48;
    }
    case 'sha512': {
      return 64;
    }
    default: {
      throw new Error('unhandled algorithm');
    }
  }
}

// Coverage (asserted by vectors.spec.ts): every digest at 600,000 plus one
// non-default count each; passwords spanning ASCII, the 15-char minimum, the
// 128-char maximum, multi-byte UTF-8, and >72 chars (bcrypt-truncation-gone).
const SEEDS: readonly Seed[] = [
  {
    algorithm: 'sha512',
    iterations: 600_000,
    label: 'sha512/600k/ascii-15char-min',
    password: 'Aa1!Bb2@Cc3#Dd4', // exactly 15 chars
  },
  {
    algorithm: 'sha512',
    iterations: 310_000,
    label: 'sha512/310k/128char-max',
    password: 'Aa1!'.repeat(32), // exactly 128 chars
  },
  {
    algorithm: 'sha256',
    iterations: 600_000,
    label: 'sha256/600k/multibyte-utf8',
    password: 'Pä1!sswörd-日本語-🔒-Secure9#',
  },
  {
    algorithm: 'sha256',
    iterations: 220_000,
    label: 'sha256/220k/over-72-chars',
    password: 'Zz9@Xx8#'.repeat(10), // 80 chars, > bcrypt's 72-byte cap
  },
  {
    algorithm: 'sha384',
    iterations: 600_000,
    label: 'sha384/600k/ascii',
    password: 'StrongPass1!Word',
  },
  {
    algorithm: 'sha384',
    iterations: 310_000,
    label: 'sha384/310k/ascii',
    password: 'AnotherPass2@Word',
  },
];

/** The vectors as data — same seeds + fixed salts → same output, always. */
export function buildVectors(): RenderedVector[] {
  return SEEDS.map((seed, index) => ({
    algorithm: seed.algorithm,
    hash: phcHash(seed, fixedSalt(index)),
    iterations: seed.iterations,
    label: seed.label,
    password: seed.password,
  }));
}

// Deterministic 32-byte salt for seed index i: byte j = (i * 31 + j) mod 256.
// Fixed and reproducible — NOT crypto.randomBytes (§14 determinism rule).
export function fixedSalt(index: number): Buffer {
  const salt = Buffer.alloc(32);
  for (let index_ = 0; index_ < salt.length; index_++) {
    salt.writeUInt8((index * 31 + index_) % 256, index_);
  }
  return salt;
}

/** The full text of src/vectors.ts. Pure and lint-clean (idempotent). */
export function renderVectorsModule(): string {
  const vectors = buildVectors();
  const entries = vectors
    .map(
      v =>
        '  {\n'
        + `    algorithm: ${sq(v.algorithm)},\n`
        + `    hash: ${sq(v.hash)},\n`
        + `    iterations: ${v.iterations},\n`
        + `    label: ${sq(v.label)},\n`
        + `    password: ${sq(v.password)},\n`
        + '  },',
    )
    .join('\n');

  // The bcrypt graceful-degradation vector (§12(4)): a PBKDF2 hash that the
  // OLD verify path (bcryptjs.compare) must reject cleanly. Reuse the first
  // known-good hash so it is a real, re-derivable PBKDF2 string.
  const degradationHash = vectors[0].hash;

  return `/**
 * GENERATED by scripts/generate-vectors.ts — DO NOT EDIT BY HAND.
 * Regenerate: npx tsx libs/password-hash-vectors/scripts/generate-vectors.ts
 *
 * Known-good password→hash vectors (ADR-006 §14, §2). Every entry's hash
 * re-derives from its password via raw node:crypto pbkdf2Sync with the
 * parameters encoded in the hash — the implementation-independent contract
 * that heimdall2's hashPassword and heimdall-cli both test against.
 */
export type PasswordHashAlgorithm = 'sha256' | 'sha384' | 'sha512';

export type KnownGoodVector = {
  readonly algorithm: PasswordHashAlgorithm;
  readonly hash: string;
  readonly iterations: number;
  readonly label: string;
  readonly password: string;
};

export const KNOWN_GOOD_VECTORS: readonly KnownGoodVector[] = [
${entries}
];

export type BcryptDegradationVector = {
  readonly expectedBcryptCompare: false;
  readonly hash: string;
};

/**
 * §12(4) rolling-deploy assertion: a pre-upgrade pod running bcryptjs.compare
 * against this PBKDF2 hash must return false without throwing. Consumed by the
 * write-gate card (e25.21).
 */
export const BCRYPT_DEGRADATION_VECTOR: BcryptDegradationVector = {
  expectedBcryptCompare: false,
  hash: ${sq(degradationHash)},
};
`;
}

// Standard base64 (not base64url), padding stripped — §2. The stored Buffer
// method is the base64 encoder available at the Node runtime (the linter's
// preferred Uint8Array#toBase64 is undefined here — see README).
function b64(buffer: Buffer): string {
  let out = buffer.toString('base64');
  while (out.endsWith('=')) {
    out = out.slice(0, -1);
  }
  return out;
}

function phcHash(seed: Seed, salt: Buffer): string {
  const key = pbkdf2Sync(
    seed.password,
    salt,
    seed.iterations,
    digestWidth(seed.algorithm),
    seed.algorithm,
  );
  return `$pbkdf2-${seed.algorithm}$i=${seed.iterations}$${b64(salt)}$${b64(key)}`;
}

// A single-quoted TS string literal, escaping backslash and single quote so
// any future seed string stays valid. Multi-byte UTF-8 passes through as-is.
function sq(value: string): string {
  return `'${value.replaceAll('\\', '\\\\').replaceAll("'", String.raw`\'`)}'`;
}
