export const githubMapping: {
  [key: string]: string;
} = {
  'apache-server-2.2-stig-baseline': 'master',
  'apache-site-2.2-stig-baseline': 'master',
  'apache-tomcat-7-cis-baseline': 'master',
  'apache-tomcat-8-cis-baseline': 'master',
  'aws-foundations-cis-baseline': 'master',
  'aws-rds-crunchy-data-postgresql-9-stig-baseline': 'master',
  'aws-rds-crunchy-data-postgresql-stig-baseline': 'master',
  'aws-rds-infrastructure-cis-baseline': 'master',
  'aws-rds-microsoft-sql-server-2014-instance-stig-baseline': 'master',
  'aws-rds-oracle-database-12c-stig-baseline': 'master',
  'aws-rds-oracle-mysql-ee-5.7-cis-baseline': 'master',
  'aws-s3-baseline': 'master',
  'canonical-ubuntu-16.04-lts-stig-baseline': 'master',
  'nical-ubuntu-20.04-lts-stig-baseline': 'main',
  'chy-data-postgresql-stig-baseline': 'main',
  'docker-ce-cis-baseline': 'master',
  'kubernetes-cis-baseline': 'master',
  'microsoft-iis-8.5-server-stig-baseline': 'master',
  'microsoft-iis-8.5-site-stig-baseline': 'master',
  'microsoft-sql-server-2014-database-stig-baseline': 'master',
  'microsoft-sql-server-2014-instance-stig-baseline': 'master',
  'microsoft-windows-10-stig-baseline': 'master',
  'microsoft-windows-2012r2-memberserver-stig-baseline': 'master',
  'microsoft-windows-server-2016-stig-baseline': 'master',
  'osoft-windows-server-2019-stig-baseline': 'main',
  'mongodb-enterprise-advanced-3-stig-baseline': 'master',
  'nginx-baseline': 'master',
  'nginx-stigready-baseline': 'master',
  'oracle-database-12c-stig-baseline': 'master',
  'oracle-java-runtime-environment-7-unix-stig-baseline': 'master',
  'oracle-java-runtime-environment-8-unix-stig-baseline': 'master',
  'oracle-mysql-ee-5.7-cis-baseline': 'master',
  'redhat-enterprise-linux-6-stig-baseline': 'master',
  'redhat-enterprise-linux-7-stig-baseline': 'main',
  'redhat-enterprise-linux-8-stig-baseline': 'main',
  'redhat-jboss-enterprise-application-platform-6.3-stig-baseline': 'master',
  'rsa-archer-6-security-configuration-guide-baseline': 'master'
};
