#!/bin/bash
set -euo pipefail

ENV_FILE="/etc/heimdall-server/backend.env"
TMP_FILE="$(mktemp)"
trap 'rm -f "${TMP_FILE}"' EXIT

usage() {
  cat >&2 <<'EOF'
Usage: heimdall-configure [--interactive|--non-interactive]

Configure /etc/heimdall-server/backend.env with connection settings and
secrets.  Missing secrets are always auto-generated.

  --interactive        Prompt for values (requires a TTY).
  --non-interactive    Accept all defaults / auto-generate everything.
  --external-url URL   Pre-set the EXTERNAL_URL value (skip prompt).

Without flags the default is --non-interactive (safe for scripted use).
EOF
}

MODE="non-interactive"
EXTERNAL_URL_OVERRIDE=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --interactive)
      MODE="interactive"
      shift
      ;;
    --non-interactive)
      shift
      ;;
    --external-url)
      if [[ $# -lt 2 ]]; then echo "--external-url requires a URL" >&2; exit 64; fi
      EXTERNAL_URL_OVERRIDE="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage
      exit 64
      ;;
  esac
done

# Load previously configured values if available.
if [[ -f "${ENV_FILE}" ]]; then
  set -a
  # shellcheck disable=SC1090
  if ! source "${ENV_FILE}"; then
    set +a
    echo "Failed to parse ${ENV_FILE}" >&2
    exit 1
  fi
  set +a
fi

NODE_ENV="${NODE_ENV:-production}"
PORT="${PORT:-3000}"
DATABASE_HOST="${DATABASE_HOST:-localhost}"
DATABASE_PORT="${DATABASE_PORT:-5432}"
DATABASE_USERNAME="${DATABASE_USERNAME:-postgres}"
DATABASE_PASSWORD="${DATABASE_PASSWORD:-}"
DATABASE_NAME="${DATABASE_NAME:-heimdall-server-${NODE_ENV}}"
JWT_SECRET="${JWT_SECRET:-$(openssl rand -hex 64)}"
JWT_EXPIRE_TIME="${JWT_EXPIRE_TIME:-1d}"
API_KEY_SECRET="${API_KEY_SECRET:-$(openssl rand -hex 33)}"
NGINX_HOST="${NGINX_HOST:-localhost}"
EXTERNAL_URL="${EXTERNAL_URL_OVERRIDE:-${EXTERNAL_URL:-}}"
ADMIN_EMAIL="${ADMIN_EMAIL:-admin@heimdall.local}"
ADMIN_PASSWORD="${ADMIN_PASSWORD:-}"

prompt_with_default() {
  local var_name="$1"
  local prompt_text="$2"
  local default_value="$3"
  local user_input=""

  printf "%s" "${prompt_text}" >/dev/tty
  read -r user_input </dev/tty

  if [[ -z "${user_input}" ]]; then
    user_input="${default_value}"
  fi

  printf -v "${var_name}" "%s" "${user_input}"
}

write_key() {
  local key="$1"
  local value="$2"
  if [[ -z "${value}" ]]; then
    printf "%s=\n" "${key}" >>"${TMP_FILE}"
    return 0
  fi

  local escaped
  # shellcheck disable=SC2016  # the single quotes are deliberate: sed must receive literal \$ patterns, not shell expansions
  escaped="$(printf "%s" "${value}" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e 's/\$/\\$/g' -e 's/`/\\`/g')"
  printf '%s="%s"\n' "${key}" "${escaped}" >>"${TMP_FILE}"
}

SHOULD_PROMPT=0
if [[ "${MODE}" == "interactive" ]]; then
  if [[ ! -t 0 && ! -t 1 && ! -t 2 ]]; then
    echo "Interactive mode requires a TTY." >&2
    exit 1
  fi
  SHOULD_PROMPT=1
fi

if [[ "${SHOULD_PROMPT}" -eq 1 ]]; then
  echo "Heimdall server configuration" >/dev/tty
  echo "Press Enter to accept each default value." >/dev/tty
  echo >/dev/tty

  prompt_with_default DATABASE_HOST     "DATABASE_HOST [${DATABASE_HOST}]: " "${DATABASE_HOST}"
  prompt_with_default DATABASE_PORT     "DATABASE_PORT [${DATABASE_PORT}]: " "${DATABASE_PORT}"
  prompt_with_default DATABASE_USERNAME "DATABASE_USERNAME [${DATABASE_USERNAME}]: " "${DATABASE_USERNAME}"
  prompt_with_default DATABASE_PASSWORD "DATABASE_PASSWORD (blank = auto-generate): " ""
  prompt_with_default DATABASE_NAME     "DATABASE_NAME [${DATABASE_NAME}]: " "${DATABASE_NAME}"
  prompt_with_default PORT              "Application PORT [${PORT}]: " "${PORT}"
  prompt_with_default JWT_EXPIRE_TIME   "JWT_EXPIRE_TIME [${JWT_EXPIRE_TIME}]: " "${JWT_EXPIRE_TIME}"
  prompt_with_default NGINX_HOST        "FQDN / Hostname / IP [${NGINX_HOST}]: " "${NGINX_HOST}"
  prompt_with_default EXTERNAL_URL      "External URL (https://...) [${EXTERNAL_URL:-https://${NGINX_HOST}}]: " "${EXTERNAL_URL:-https://${NGINX_HOST}}"
  prompt_with_default ADMIN_EMAIL       "Initial admin email [${ADMIN_EMAIL}]: " "${ADMIN_EMAIL}"
fi

PASSWORD_AUTO_GENERATED=0
if [[ -z "${DATABASE_USERNAME//[[:space:]]/}" ]]; then
  DATABASE_USERNAME="postgres"
fi

if [[ -z "${DATABASE_PASSWORD//[[:space:]]/}" ]]; then
  DATABASE_PASSWORD="$(openssl rand -hex 33)"
  PASSWORD_AUTO_GENERATED=1
fi

printf "# Generated by heimdall-server-setup\n" >"${TMP_FILE}"
write_key NODE_ENV "${NODE_ENV}"
write_key PORT "${PORT}"
write_key DATABASE_HOST "${DATABASE_HOST}"
write_key DATABASE_PORT "${DATABASE_PORT}"
write_key DATABASE_USERNAME "${DATABASE_USERNAME}"
write_key DATABASE_PASSWORD "${DATABASE_PASSWORD}"
write_key DATABASE_NAME "${DATABASE_NAME}"
write_key JWT_SECRET "${JWT_SECRET}"
write_key JWT_EXPIRE_TIME "${JWT_EXPIRE_TIME}"
write_key API_KEY_SECRET "${API_KEY_SECRET}"
write_key NGINX_HOST "${NGINX_HOST}"
write_key EXTERNAL_URL "${EXTERNAL_URL:-https://${NGINX_HOST}}"
write_key ADMIN_EMAIL "${ADMIN_EMAIL}"
write_key ADMIN_PASSWORD "${ADMIN_PASSWORD}"

mv "${TMP_FILE}" "${ENV_FILE}"
chown root:heimdall "${ENV_FILE}"
chmod 0640 "${ENV_FILE}"

echo "Configuration saved to ${ENV_FILE}"
if [[ "${PASSWORD_AUTO_GENERATED}" -eq 1 ]]; then
  echo "DATABASE_PASSWORD was auto-generated (a secure random value)."
fi
