"""
Heimdall Server configuration schema.

Defines all backend.env keys with categories, types, defaults, validation,
and descriptions. Used by heimdall-cli for config get/set, tab completion,
setup wizards, and documentation generation.
"""

# Valid types: str, int, bool, secret, url, email, path
# 'secret' behaves like str but is masked in output and generated randomly

CONFIG_SCHEMA = {
    # ── Core ────────────────────────────────────────────────────────────
    'NODE_ENV': {
        'category': 'core',
        'type': 'str',
        'default': 'production',
        'choices': ['production', 'development', 'test'],
        'description': 'Application environment.',
        'required': True,
    },
    'HEIMDALL_BACKEND_PORT': {
        'category': 'core',
        'type': 'int',
        'default': '3000',
        'validation': '1-65535',
        'description': 'HTTP listen port for the Heimdall backend.',
    },
    'EXTERNAL_URL': {
        'category': 'core',
        'type': 'url',
        'default': '',
        'description': 'Public URL users access Heimdall at. Required for OAuth callbacks.',
        'example': 'https://heimdall.example.com',
    },
    'NGINX_HOST': {
        'category': 'core',
        'type': 'str',
        'default': 'localhost',
        'description': 'Hostname used by frontend defaults.',
    },
    'LOG_FILE': {
        'category': 'core',
        'type': 'path',
        'default': '',
        'description': 'Log file path. If unset, logs go to journald. '
                       'Example: /var/log/heimdall-server/server.log',
        'example': '/var/log/heimdall-server/server.log',
    },

    # ── Database ────────────────────────────────────────────────────────
    'DATABASE_HOST': {
        'category': 'database',
        'type': 'str',
        'default': 'localhost',
        'description': 'PostgreSQL hostname.',
    },
    'DATABASE_PORT': {
        'category': 'database',
        'type': 'int',
        'default': '5432',
        'validation': '1-65535',
        'description': 'PostgreSQL port.',
    },
    'DATABASE_USERNAME': {
        'category': 'database',
        'type': 'str',
        'default': 'postgres',
        'description': 'PostgreSQL username.',
    },
    'DATABASE_PASSWORD': {
        'category': 'database',
        'type': 'secret',
        'default': '',
        'description': 'PostgreSQL password.',
        'required': True,
    },
    'DATABASE_NAME': {
        'category': 'database',
        'type': 'str',
        'default': 'heimdall-server-production',
        'description': 'Database name.',
    },
    'DATABASE_URL': {
        'category': 'database',
        'type': 'url',
        'default': '',
        'description': 'Full connection URL. Overrides individual DB settings if set.',
        'example': 'postgresql://user:pass@host:5432/dbname',
    },
    'DATABASE_SSL': {
        'category': 'database',
        'type': 'bool',
        'default': 'false',
        'description': 'Enable SSL for database connection.',
    },
    'DATABASE_SSL_KEY': {
        'category': 'database',
        'type': 'path',
        'default': '',
        'description': 'SSL key file path or PEM content.',
    },
    'DATABASE_SSL_CERT': {
        'category': 'database',
        'type': 'path',
        'default': '',
        'description': 'SSL certificate file path or PEM content.',
    },
    'DATABASE_SSL_CA': {
        'category': 'database',
        'type': 'path',
        'default': '',
        'description': 'SSL CA certificate file path or PEM content.',
    },
    'DATABASE_SSL_INSECURE': {
        'category': 'database',
        'type': 'bool',
        'default': 'false',
        'description': 'Skip SSL certificate verification.',
    },

    # ── Authentication ──────────────────────────────────────────────────
    'JWT_SECRET': {
        'category': 'auth',
        'type': 'secret',
        'default': '',
        'description': 'Secret key for JWT signing. Auto-generated by setup.',
        'required': True,
        'generate': 'openssl rand -hex 33',
    },
    'JWT_EXPIRE_TIME': {
        'category': 'auth',
        'type': 'str',
        'default': '1d',
        'description': 'JWT expiration duration (e.g., 60s, 1h, 1d).',
    },
    'API_KEY_SECRET': {
        'category': 'auth',
        'type': 'secret',
        'default': '',
        'description': 'Secret for API key generation. Leave blank to disable API keys.',
        'generate': 'openssl rand -hex 33',
    },
    'ADMIN_EMAIL': {
        'category': 'auth',
        'type': 'email',
        'default': 'admin@heimdall.local',
        'description': 'Initial admin user email (used during db:seed).',
    },
    'ADMIN_PASSWORD': {
        'category': 'auth',
        'type': 'secret',
        'default': '',
        'description': 'Initial admin password. Auto-generated if blank.',
    },
    'ADMIN_USES_EXTERNAL_AUTH': {
        'category': 'auth',
        'type': 'bool',
        'default': 'false',
        'description': 'Admin authenticates via external provider instead of local.',
    },
    'LOCAL_LOGIN_DISABLED': {
        'category': 'auth',
        'type': 'bool',
        'default': 'false',
        'description': 'Disable local username/password login.',
    },
    'REGISTRATION_DISABLED': {
        'category': 'auth',
        'type': 'bool',
        'default': 'false',
        'description': 'Disable public user registration.',
    },
    'ONE_SESSION_PER_USER': {
        'category': 'auth',
        'type': 'bool',
        'default': 'false',
        'description': 'Only allow one active session per user.',
    },
    'MAX_FILE_UPLOAD_SIZE': {
        'category': 'auth',
        'type': 'int',
        'default': '50',
        'description': 'Maximum evaluation upload size in MB.',
    },

    # ── UI / Branding ───────────────────────────────────────────────────
    'WARNING_BANNER': {
        'category': 'ui',
        'type': 'str',
        'default': '',
        'description': 'Warning banner text displayed to users.',
    },
    'CLASSIFICATION_BANNER_TEXT': {
        'category': 'ui',
        'type': 'str',
        'default': '',
        'description': 'Classification banner text (e.g., CUI, FOUO).',
    },
    'CLASSIFICATION_BANNER_TEXT_COLOR': {
        'category': 'ui',
        'type': 'str',
        'default': 'white',
        'description': 'Classification banner text color.',
    },
    'CLASSIFICATION_BANNER_COLOR': {
        'category': 'ui',
        'type': 'str',
        'default': 'red',
        'description': 'Classification banner background color.',
    },

    # ── GitHub OAuth ────────────────────────────────────────────────────
    'GITHUB_CLIENTID': {
        'category': 'github',
        'type': 'str',
        'default': '',
        'description': 'GitHub OAuth app client ID. Set to enable GitHub login.',
        'provider': 'github',
        'enables_provider': True,
    },
    'GITHUB_CLIENTSECRET': {
        'category': 'github',
        'type': 'secret',
        'default': '',
        'description': 'GitHub OAuth app client secret.',
        'provider': 'github',
    },
    'GITHUB_ENTERPRISE_INSTANCE_BASE_URL': {
        'category': 'github',
        'type': 'url',
        'default': 'https://github.com/',
        'description': 'GitHub Enterprise base URL.',
        'provider': 'github',
        'example': 'https://github.example.com/',
    },
    'GITHUB_ENTERPRISE_INSTANCE_API_URL': {
        'category': 'github',
        'type': 'url',
        'default': 'https://api.github.com/',
        'description': 'GitHub Enterprise API URL.',
        'provider': 'github',
        'example': 'https://github.example.com/api/v3/',
    },

    # ── GitLab OAuth ────────────────────────────────────────────────────
    'GITLAB_CLIENTID': {
        'category': 'gitlab',
        'type': 'str',
        'default': '',
        'description': 'GitLab OAuth app client ID. Set to enable GitLab login.',
        'provider': 'gitlab',
        'enables_provider': True,
    },
    'GITLAB_CLIENTSECRET': {
        'category': 'gitlab',
        'type': 'secret',
        'default': '',
        'description': 'GitLab OAuth app client secret.',
        'provider': 'gitlab',
    },
    'GITLAB_BASEURL': {
        'category': 'gitlab',
        'type': 'url',
        'default': 'https://gitlab.com',
        'description': 'GitLab instance URL.',
        'provider': 'gitlab',
    },

    # ── Google OAuth ────────────────────────────────────────────────────
    'GOOGLE_CLIENTID': {
        'category': 'google',
        'type': 'str',
        'default': '',
        'description': 'Google OAuth client ID. Set to enable Google login.',
        'provider': 'google',
        'enables_provider': True,
    },
    'GOOGLE_CLIENTSECRET': {
        'category': 'google',
        'type': 'secret',
        'default': '',
        'description': 'Google OAuth client secret.',
        'provider': 'google',
    },

    # ── Okta OIDC ───────────────────────────────────────────────────────
    'OKTA_DOMAIN': {
        'category': 'okta',
        'type': 'str',
        'default': '',
        'description': 'Okta domain (e.g., your-org.okta.com).',
        'provider': 'okta',
        'example': 'your-org.okta.com',
    },
    'OKTA_CLIENTID': {
        'category': 'okta',
        'type': 'str',
        'default': '',
        'description': 'Okta OAuth app client ID. Set to enable Okta login.',
        'provider': 'okta',
        'enables_provider': True,
    },
    'OKTA_CLIENTSECRET': {
        'category': 'okta',
        'type': 'secret',
        'default': '',
        'description': 'Okta OAuth app client secret.',
        'provider': 'okta',
    },
    'OKTA_ISSUER_URL': {
        'category': 'okta',
        'type': 'url',
        'default': '',
        'description': 'Okta issuer URL. Auto-computed from OKTA_DOMAIN if not set.',
        'provider': 'okta',
    },
    'OKTA_AUTHORIZATION_URL': {
        'category': 'okta',
        'type': 'url',
        'default': '',
        'description': 'Okta authorization endpoint. Auto-computed from OKTA_DOMAIN.',
        'provider': 'okta',
    },
    'OKTA_TOKEN_URL': {
        'category': 'okta',
        'type': 'url',
        'default': '',
        'description': 'Okta token endpoint. Auto-computed from OKTA_DOMAIN.',
        'provider': 'okta',
    },
    'OKTA_USER_INFO_URL': {
        'category': 'okta',
        'type': 'url',
        'default': '',
        'description': 'Okta userinfo endpoint. Auto-computed from OKTA_DOMAIN.',
        'provider': 'okta',
    },
    'OKTA_USE_HTTPS_PROXY': {
        'category': 'okta',
        'type': 'bool',
        'default': 'false',
        'description': 'Route Okta requests through HTTPS_PROXY.',
        'provider': 'okta',
    },

    # ── Generic OIDC ────────────────────────────────────────────────────
    'OIDC_NAME': {
        'category': 'oidc',
        'type': 'str',
        'default': '',
        'description': 'Display name for OIDC provider (shown on login page).',
        'provider': 'oidc',
        'example': 'My Identity Provider',
    },
    'OIDC_ISSUER': {
        'category': 'oidc',
        'type': 'url',
        'default': '',
        'description': 'OIDC provider issuer URL.',
        'provider': 'oidc',
        'example': 'https://auth.example.com',
    },
    'OIDC_AUTHORIZATION_URL': {
        'category': 'oidc',
        'type': 'url',
        'default': '',
        'description': 'OIDC authorization endpoint.',
        'provider': 'oidc',
    },
    'OIDC_TOKEN_URL': {
        'category': 'oidc',
        'type': 'url',
        'default': '',
        'description': 'OIDC token endpoint.',
        'provider': 'oidc',
    },
    'OIDC_USER_INFO_URL': {
        'category': 'oidc',
        'type': 'url',
        'default': '',
        'description': 'OIDC userinfo endpoint.',
        'provider': 'oidc',
    },
    'OIDC_CLIENTID': {
        'category': 'oidc',
        'type': 'str',
        'default': '',
        'description': 'OIDC client ID. Set to enable generic OIDC login.',
        'provider': 'oidc',
        'enables_provider': True,
    },
    'OIDC_CLIENT_SECRET': {
        'category': 'oidc',
        'type': 'secret',
        'default': '',
        'description': 'OIDC client secret.',
        'provider': 'oidc',
    },
    'OIDC_USE_HTTPS_PROXY': {
        'category': 'oidc',
        'type': 'bool',
        'default': 'false',
        'description': 'Route OIDC requests through HTTPS_PROXY.',
        'provider': 'oidc',
    },
    'OIDC_USES_PKCE_S256': {
        'category': 'oidc',
        'type': 'bool',
        'default': 'false',
        'description': 'Use PKCE with SHA-256 challenge method.',
        'provider': 'oidc',
    },
    'OIDC_USES_PKCE_PLAIN': {
        'category': 'oidc',
        'type': 'bool',
        'default': 'false',
        'description': 'Use PKCE with plain text challenge method.',
        'provider': 'oidc',
    },
    'OIDC_USES_VERIFIED_EMAIL': {
        'category': 'oidc',
        'type': 'bool',
        'default': 'true',
        'description': 'Require verified email from OIDC provider.',
        'provider': 'oidc',
    },
    'OIDC_EXTERNAL_GROUPS': {
        'category': 'oidc',
        'type': 'bool',
        'default': 'false',
        'description': 'Synchronize user groups from OIDC provider claims.',
        'provider': 'oidc',
    },

    # ── LDAP ────────────────────────────────────────────────────────────
    'LDAP_ENABLED': {
        'category': 'ldap',
        'type': 'bool',
        'default': 'false',
        'description': 'Enable LDAP authentication.',
        'provider': 'ldap',
        'enables_provider': True,
    },
    'LDAP_HOST': {
        'category': 'ldap',
        'type': 'str',
        'default': '',
        'description': 'LDAP server hostname.',
        'provider': 'ldap',
        'example': 'ldap.example.com',
    },
    'LDAP_PORT': {
        'category': 'ldap',
        'type': 'int',
        'default': '389',
        'validation': '1-65535',
        'description': 'LDAP server port.',
        'provider': 'ldap',
    },
    'LDAP_BINDDN': {
        'category': 'ldap',
        'type': 'str',
        'default': '',
        'description': 'Bind DN for LDAP lookups.',
        'provider': 'ldap',
        'example': 'cn=admin,dc=example,dc=com',
    },
    'LDAP_PASSWORD': {
        'category': 'ldap',
        'type': 'secret',
        'default': '',
        'description': 'Bind password for LDAP lookups.',
        'provider': 'ldap',
    },
    'LDAP_SEARCHBASE': {
        'category': 'ldap',
        'type': 'str',
        'default': '',
        'description': 'LDAP search base DN.',
        'provider': 'ldap',
        'example': 'OU=Users,DC=example,DC=com',
    },
    'LDAP_SEARCHFILTER': {
        'category': 'ldap',
        'type': 'str',
        'default': '(sAMAccountName={{username}})',
        'description': 'LDAP search filter. {{username}} is replaced at login.',
        'provider': 'ldap',
    },
    'LDAP_NAMEFIELD': {
        'category': 'ldap',
        'type': 'str',
        'default': 'name',
        'description': 'LDAP attribute containing display name.',
        'provider': 'ldap',
    },
    'LDAP_MAILFIELD': {
        'category': 'ldap',
        'type': 'str',
        'default': 'mail',
        'description': 'LDAP attribute containing email address.',
        'provider': 'ldap',
    },
    'LDAP_SSL': {
        'category': 'ldap',
        'type': 'bool',
        'default': 'false',
        'description': 'Use SSL for LDAP connections.',
        'provider': 'ldap',
    },
    'LDAP_SSL_INSECURE': {
        'category': 'ldap',
        'type': 'bool',
        'default': 'false',
        'description': 'Skip LDAP SSL certificate verification.',
        'provider': 'ldap',
    },
    'LDAP_SSL_CA': {
        'category': 'ldap',
        'type': 'path',
        'default': '',
        'description': 'LDAP SSL CA certificate file path or PEM content.',
        'provider': 'ldap',
    },

    # ── Proxy ───────────────────────────────────────────────────────────
    'HTTPS_PROXY': {
        'category': 'proxy',
        'type': 'url',
        'default': '',
        'description': 'HTTPS proxy URL for OAuth/OIDC outbound requests.',
        'example': 'http://proxy.example.com:8080',
    },
    'NODE_EXTRA_CA_CERTS': {
        'category': 'proxy',
        'type': 'path',
        'default': '',
        'description': 'Path to CA bundle for TLS inspection proxies.',
        'example': '/etc/pki/tls/certs/ca-bundle.crt',
    },

    # ── External Services ───────────────────────────────────────────────
    'TENABLE_HOST_URL': {
        'category': 'integrations',
        'type': 'url',
        'default': '',
        'description': 'Tenable.SC instance URL.',
    },
    'SPLUNK_HOST_URL': {
        'category': 'integrations',
        'type': 'url',
        'default': '',
        'description': 'Splunk instance URL.',
    },
    'FORCE_TENABLE_FRONTEND': {
        'category': 'integrations',
        'type': 'bool',
        'default': 'false',
        'description': 'Force Tenable.SC UI on frontend.',
    },
}

# Category metadata for display and grouping
CATEGORIES = {
    'core':         {'label': 'Core',                'order': 0},
    'database':     {'label': 'Database',            'order': 1},
    'auth':         {'label': 'Authentication',      'order': 2},
    'ui':           {'label': 'UI / Branding',       'order': 3},
    'github':       {'label': 'GitHub OAuth',        'order': 4},
    'gitlab':       {'label': 'GitLab OAuth',        'order': 5},
    'google':       {'label': 'Google OAuth',        'order': 6},
    'okta':         {'label': 'Okta OIDC',           'order': 7},
    'oidc':         {'label': 'Generic OIDC',        'order': 8},
    'ldap':         {'label': 'LDAP',                'order': 9},
    'proxy':        {'label': 'Proxy / TLS',         'order': 10},
    'integrations': {'label': 'External Services',   'order': 11},
}

# Auth provider definitions for setup wizards
PROVIDERS = {
    'github': {
        'label': 'GitHub',
        'required_keys': ['GITHUB_CLIENTID', 'GITHUB_CLIENTSECRET'],
        'optional_keys': ['GITHUB_ENTERPRISE_INSTANCE_BASE_URL',
                          'GITHUB_ENTERPRISE_INSTANCE_API_URL'],
        'needs_external_url': True,
        'docs_url': 'https://docs.github.com/en/apps/oauth-apps/building-oauth-apps',
    },
    'gitlab': {
        'label': 'GitLab',
        'required_keys': ['GITLAB_CLIENTID', 'GITLAB_CLIENTSECRET'],
        'optional_keys': ['GITLAB_BASEURL'],
        'needs_external_url': True,
        'docs_url': 'https://docs.gitlab.com/ee/integration/oauth_provider.html',
    },
    'google': {
        'label': 'Google',
        'required_keys': ['GOOGLE_CLIENTID', 'GOOGLE_CLIENTSECRET'],
        'optional_keys': [],
        'needs_external_url': True,
        'docs_url': 'https://console.cloud.google.com/apis/credentials',
    },
    'okta': {
        'label': 'Okta',
        'required_keys': ['OKTA_DOMAIN', 'OKTA_CLIENTID', 'OKTA_CLIENTSECRET'],
        'optional_keys': ['OKTA_ISSUER_URL', 'OKTA_AUTHORIZATION_URL',
                          'OKTA_TOKEN_URL', 'OKTA_USER_INFO_URL',
                          'OKTA_USE_HTTPS_PROXY'],
        'needs_external_url': True,
        'docs_url': 'https://developer.okta.com/docs/guides/sign-into-web-app/nodeexpress/main/',
    },
    'oidc': {
        'label': 'Generic OIDC',
        'required_keys': ['OIDC_NAME', 'OIDC_ISSUER', 'OIDC_AUTHORIZATION_URL',
                          'OIDC_TOKEN_URL', 'OIDC_USER_INFO_URL',
                          'OIDC_CLIENTID', 'OIDC_CLIENT_SECRET'],
        'optional_keys': ['OIDC_USE_HTTPS_PROXY', 'OIDC_USES_PKCE_S256',
                          'OIDC_USES_PKCE_PLAIN', 'OIDC_USES_VERIFIED_EMAIL',
                          'OIDC_EXTERNAL_GROUPS'],
        'needs_external_url': True,
        'docs_url': 'https://openid.net/developers/how-connect-works/',
    },
    'ldap': {
        'label': 'LDAP',
        'required_keys': ['LDAP_ENABLED', 'LDAP_HOST', 'LDAP_PORT',
                          'LDAP_BINDDN', 'LDAP_PASSWORD', 'LDAP_SEARCHBASE'],
        'optional_keys': ['LDAP_SEARCHFILTER', 'LDAP_NAMEFIELD',
                          'LDAP_MAILFIELD', 'LDAP_SSL', 'LDAP_SSL_INSECURE',
                          'LDAP_SSL_CA'],
        'needs_external_url': False,
    },
}


def keys_for_category(category):
    """Return config keys belonging to a category, in definition order."""
    return [k for k, v in CONFIG_SCHEMA.items() if v['category'] == category]


def keys_for_provider(provider):
    """Return all config keys for an auth provider."""
    return [k for k, v in CONFIG_SCHEMA.items()
            if v.get('provider') == provider]


def all_keys():
    """Return all config key names."""
    return list(CONFIG_SCHEMA.keys())


def required_keys():
    """Return keys marked as required."""
    return [k for k, v in CONFIG_SCHEMA.items() if v.get('required')]


def secret_keys():
    """Return keys of type 'secret'."""
    return [k for k, v in CONFIG_SCHEMA.items() if v['type'] == 'secret']
