export type KnownGoodVector = {
  readonly algorithm: PasswordHashAlgorithm;
  readonly hash: string;
  readonly iterations: number;
  readonly label: string;
  readonly password: string;
};

/**
 * GENERATED by scripts/generate-vectors.ts — DO NOT EDIT BY HAND.
 * Regenerate: npx tsx libs/password-hash-vectors/scripts/generate-vectors.ts
 *
 * Known-good password→hash vectors (ADR-006 §14, §2). Every entry's hash
 * re-derives from its password via raw node:crypto pbkdf2Sync with the
 * parameters encoded in the hash — the implementation-independent contract
 * that heimdall2's hashPassword and heimdall-cli both test against.
 */
export type PasswordHashAlgorithm = 'sha256' | 'sha384' | 'sha512';

export const KNOWN_GOOD_VECTORS: readonly KnownGoodVector[] = [
  {
    algorithm: 'sha512',
    hash: '$pbkdf2-sha512$i=600000$AAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8$Jak+mPMZR0uTl9aahxqJj7bizgRxx+uPvohGrHh9NiKgRhyFGoQHvdz4l62bwdOIkDzG7wmKqe2iY8oPvyd0MQ',
    iterations: 600_000,
    label: 'sha512/600k/ascii-15char-min',
    password: 'Aa1!Bb2@Cc3#Dd4',
  },
  {
    algorithm: 'sha512',
    hash: '$pbkdf2-sha512$i=310000$HyAhIiMkJSYnKCkqKywtLi8wMTIzNDU2Nzg5Ojs8PT4$9rcsQqmO94zDag3Yp2n011B8MfYzOgN6vngfy/asRDhbXD54vLXjxytomSOd3L8JClKHHlpGGpOWHUJ2s0EEwg',
    iterations: 310_000,
    label: 'sha512/310k/128char-max',
    password: 'Aa1!Aa1!Aa1!Aa1!Aa1!Aa1!Aa1!Aa1!Aa1!Aa1!Aa1!Aa1!Aa1!Aa1!Aa1!Aa1!Aa1!Aa1!Aa1!Aa1!Aa1!Aa1!Aa1!Aa1!Aa1!Aa1!Aa1!Aa1!Aa1!Aa1!Aa1!Aa1!',
  },
  {
    algorithm: 'sha256',
    hash: '$pbkdf2-sha256$i=600000$Pj9AQUJDREVGR0hJSktMTU5PUFFSU1RVVldYWVpbXF0$t6eIoLnlVZnKgtZ0Mhszm2vT9EvQ9bG1TVwqA0Nlfo4',
    iterations: 600_000,
    label: 'sha256/600k/multibyte-utf8',
    password: 'Pä1!sswörd-日本語-🔒-Secure9#',
  },
  {
    algorithm: 'sha256',
    hash: '$pbkdf2-sha256$i=220000$XV5fYGFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6e3w$GIX4ljrgztG9iRBf7Y6HFOCIT5LfW2DsLmL+cMCGLNc',
    iterations: 220_000,
    label: 'sha256/220k/over-72-chars',
    password: 'Zz9@Xx8#Zz9@Xx8#Zz9@Xx8#Zz9@Xx8#Zz9@Xx8#Zz9@Xx8#Zz9@Xx8#Zz9@Xx8#Zz9@Xx8#Zz9@Xx8#',
  },
  {
    algorithm: 'sha384',
    hash: '$pbkdf2-sha384$i=600000$fH1+f4CBgoOEhYaHiImKi4yNjo+QkZKTlJWWl5iZmps$qIeGzbMys6rj5rbSWOu9yYNVj7T6BGy3g0IemZ20y77EJj0M14GEzgMBrz8WxBK1',
    iterations: 600_000,
    label: 'sha384/600k/ascii',
    password: 'StrongPass1!Word',
  },
  {
    algorithm: 'sha384',
    hash: '$pbkdf2-sha384$i=310000$m5ydnp+goaKjpKWmp6ipqqusra6vsLGys7S1tre4ubo$Im7eDvMpXAo+IxxHn3eHmMCtUO+FRLUGtLRToMVvxB0gR0snAY0QuSXd8rxqsh31',
    iterations: 310_000,
    label: 'sha384/310k/ascii',
    password: 'AnotherPass2@Word',
  },
];

export type BcryptDegradationVector = {
  readonly expectedBcryptCompare: false;
  readonly hash: string;
};

/**
 * §12(4) rolling-deploy assertion: a pre-upgrade pod running bcryptjs.compare
 * against this PBKDF2 hash must return false without throwing. Consumed by the
 * write-gate card (e25.21).
 */
export const BCRYPT_DEGRADATION_VECTOR: BcryptDegradationVector = {
  expectedBcryptCompare: false,
  hash: '$pbkdf2-sha512$i=600000$AAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8$Jak+mPMZR0uTl9aahxqJj7bizgRxx+uPvohGrHh9NiKgRhyFGoQHvdz4l62bwdOIkDzG7wmKqe2iY8oPvyd0MQ',
};
