name: SBOM Generator

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      # Anchore Syft Github Action
      - name: Build the Docker image
        if: always()
        run: docker build -f Dockerfile -t mitre/heimdall2:throwaway .
        
      - name: Syft directory spdx
        if: always()
        uses: anchore/sbom-action@v0
        with:
          artifact-name: syft_directory.spdx.json
          output-file: /tmp/syft_directory.spdx.json
          format: spdx-json

      - name: Syft directory spdx converted
        if: always()
        run: docker run -t -v /tmp/syft_directory.spdx.json:/tmp/syft_directory.spdx.json -v /tmp/syft_directory_spdx.cdx.json:/tmp/syft_directory_spdx.cdx.json cyclonedx/cyclonedx-cli:latest convert --input-file /tmp/syft_directory.spdx.json --output-file /tmp/syft_directory_spdx.cdx.json  --input-format spdxjson --output-format json 
          
      - name: Syft directory cyclonedx
        if: always()
        uses: anchore/sbom-action@v0
        with:
          artifact-name: syft_directory.cdx.json
          output-file: /tmp/syft_directory.cdx.json
          format: cyclonedx-json

      - name: Syft image spdx
        if: always()
        uses: anchore/sbom-action@v0
        with:
          image: "mitre/heimdall2:throwaway"
          artifact-name: syft_image.spdx.json
          output-file: /tmp/syft_image.spdx.json
          format: spdx-json
          
      - name: Syft image spdx converted
        if: always()
        run: docker run -t -v /tmp/syft_image.spdx.json:/tmp/syft_image.spdx.json -v /tmp/syft_image_spdx.cdx.json:/tmp/syft_image_spdx.cdx.json cyclonedx/cyclonedx-cli:latest convert --input-file /tmp/syft_image.spdx.json --output-file /tmp/syft_image_spdx.cdx.json  --input-format spdxjson --output-format json 
   
      - name: Syft image cyclonedx
        if: always()
        uses: anchore/sbom-action@v0
        with:
          image: "mitre/heimdall2:throwaway"
          artifact-name: syft_image.cdx.json
          output-file: /tmp/syft_image.cdx.json
          format: cyclonedx-json

      - uses: actions/upload-artifact@v4
        if: always()
        with: 
          path: /tmp/syft*
          name: "Syft SBOM experiments"
