name: SBOM Generator

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      # Github Advanced Security CLI # TODO: we can apparently run into issues with rate limits if we hit the gh api too much.  once we get rid of all the spurious ones, it should probably be fine but if not we might need to restrict it to just run against master or even just release.
      - name: Install Github CLI SBOM extension
        if: always()
        run: gh ext install advanced-security/gh-sbom
        env: 
          GITHUB_TOKEN: ${{ github.token }}

      - name: Run Github Advanced Security CLI CDX
        if: always()
        run: gh sbom -c -l | jq '.' > /tmp/ghas_cli_sbom.cdx.json
        env: 
          GITHUB_TOKEN: ${{ github.token }}

      - uses: actions/upload-artifact@v4
        if: always()
        with: 
          path: /tmp/ghas_cli_sbom.cdx.json
          name: "Github SBOM CLI.cdx.json"

      # Anchore Syft Github Action

      - run: ls
        if: always()

      - run: tree
        if: always()
